### ISSUE TITLE
r-devel and R CMD check --as-cran: checking CRAN incoming feasibility ...Warning: unable to access index

### ISSUE THREAD

**Issue by kforner** [rocker-org/rocker#102]
Hello,
When using R in the r-devel rocker to check a package (e.g. testthat), I get:
```
* this is package ‘testthat’ version ‘0.9.1.9001’
* checking CRAN incoming feasibility ...Warning: unable to access index for repository NULL/src/contrib
Warning: unable to access index for repository NULL/src/contrib
Warning: unable to access index for repository NULL/src/contrib
NB: need Internet access to use CRAN incoming checks
```
Any idea from the source of the problem ?

Full reproducible example:
```
docker run --rm -ti rocker/r-devel bash
%R
>install.packages("digest")
>install.packages("crayon")
>download.packages("testthat", ".")
>q()
%R CMD check --as-cran testthat_*.tar.gz
```

works fine with RD

Thanks
Karl

**Comment by eddelbuettel** [comment]
Fully reproducible examples please. Show your invocation.

I can reproduce this by adding `--as-cran` to `R CMD check`, but I'd file this as an R(-release) bug because
a) `RD CMD check --as-cran` works (ie use r-devel)
b) internet and CRAN access works as I can do 'install.r somePackage' to get somePackage from CRAN.

**Comment by cboettig** [comment]
please re-open if this issue persists.
