### ISSUE TITLE
In r-base a user 'docker' is created but CMD runs R as 'root'

### ISSUE THREAD

**Issue by krrrcks** [rocker-org/rocker#103]
A new user 'docker' is added but the CMD is run as root:

```
~> docker run -it --rm rocker/r-base 

R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

(...)

> system(command="id")
uid=0(root) gid=0(root) groups=0(root)
> 
```

If R should be run as a "normal user" I would suggest to add a line `USER docker` to the Dockerfile just before the CMD line:

```
diff --git a/r-base/Dockerfile b/r-base/Dockerfile
index 601bce4..8219eaa 100644
--- a/r-base/Dockerfile
+++ b/r-base/Dockerfile
@@ -53,4 +53,6 @@ RUN apt-get update -qq \
 ## Set a default CRAN Repo
 RUN echo 'options(repos = list(CRAN = "http://cran.rstudio.com/"))' >> /etc/R/Rprofile.site
 
+USER docker
+
 CMD ["R"]
```

Or if R should be run as 'root' I would suggest to remove the creation of the 'docker' user.

**Comment by eddelbuettel** [comment]
Hm, fair point, though I have the feeling @cboettig has been over all these motions...   

We also got an implicit/explicit code review from the Docker folks when this got "blessed" for R.  But I am otherwise with you.

If we change to `docker`, we need to make sure we can still write as docker in /usr/local/lib/R/site-library; one way to do so is to make docker a member of 'adm' which is the group I set there in the R package:

```{sh}
edd@max:~/svn/r-devel$ docker run -ti --rm r-base /bin/bash
root@ed3bba169dd7:/# ls -ld /usr/local/lib/R/site-library/
drwxrwsr-x 4 root staff 4096 Jan  1 09:12 /usr/local/lib/R/site-library/
root@ed3bba169dd7:/# 
```

**Comment by krrrcks** [comment]
Well, to me it seems to work, I created that Dockerfile

``` 
FROM rocker/r-base

USER docker
CMD ["R"]
```

Then:
```
$> docker run -ti --rm foo

R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

(...)

> install.packages("plyr")

(... scroll removed ...)

> system("id")
uid=1000(docker) gid=1000(docker) groups=1000(docker),50(staff)
> system("ls /usr/local/lib/R/site-library")
docopt	plyr  Rcpp  stringr
> 
```


I am not sure about the "best practice. For development on my local machine I often avoid swtiching to a separate user but in production environments I would suggest to have a non-root account.

**Comment by eddelbuettel** [comment]
Good. We seem to have taken care of that then for that very reason, and I had forgotten about it.

Non-root is a good idea.

**Comment by cboettig** [comment]
I think we should leave this the way it is, this is very intentional.  A docker user can always run as non-root by passing the command `--user=docker` at runtime.  This is why we add the user in the first place; this would not work otherwise.  The docker user is already a member of `staff` so they can install packages in the same place etc.

The reason we don't run as `docker` by default is that it makes for a cumbersome base image when writing other dockerfiles.  Most (all official?) base images leave the default user as root.  This way, someone who uses `FROME r-base` doesn't need to switch back and forth to the root user with a `USER root` (switching back and forth adds extra layers and is against the best practices advised by Docker, as is using `sudo` in Dockerfiles).  Changing this would almost certainly break every Dockerfile built on r-base.

**Comment by eddelbuettel** [comment]
Dang. Spot on. I should have remembered.  

Maybe carry these two paras over to the wiki?

**Comment by krrrcks** [comment]
Yeah, I understand and agree! Would perhaps be great to have these hints and reasons in the documentation/wiki.

**Comment by krrrcks** [comment]
Although I am using docker a lot during development and even have some production environments with docker I was not aware of this "best practice". Sounds reasonable. Thanks for your insights and sorry for the noise. :/

**Comment by cboettig** [comment]
@krrrcks no problem, it always helps to hear what users are doing so we can fix the documentation if not the Dockerfiles.  

I've added a page to the wiki now: https://github.com/rocker-org/rocker/wiki/managing-users-in-docker lemme know what you think (feel free to edit the wiki directly or open new issues).  There's some mention of this on the 'sharing volumes' page as well (but not the justification), since using a non-root user seems less critical when not sharing volumes as the container is more isolated from the host then.
