### ISSUE TITLE
Can rocker run GUIs written in R?

### ISSUE THREAD

**Issue by sje30** [rocker-org/rocker#110]
Hi Dirk/Carl,

I couldn't find much out there regarding running GUI applications in docker.  A friend (@DavidCSterratt) has written a great R package (http://retistruct.r-forge.r-project.org/); it uses RGtk2 package, and so doesn't run on modern macs, which is a shame.

I suggested to him that maybe docker could be used as a workaround for those on macs wanting to run his software - but neither of us are sure if docker provides a environment for running Gtk apps -- is it possible?

Thanks, Stephen

**Comment by cboettig** [comment]
Hi Stephen,

Well, I guess it depends what you mean by "possible"... (Or what you mean by "GUI application" -- a GUI application that runs in a brower, like RStudio server, will clearly work...)

You cannot interact with X11/GTK based packages from RStudio server, since X11 isn't running there.  

You can install an ssh client onto a rocker container and connect to it with any of the various flavors of X forwarding.  I assume that you'd have to have X11 installed on the host for this to work, and from your comment it sounds like this is non-trivial on a Mac?

**Comment by eddelbuettel** [comment]
Stephen,

To a first approximation, Docker is a shield for a process.  Plus bells and whistles.  There are in fact HOWTOs on doing desktop apps via Docker eg [this is an older one](http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/) but that does not overcome the basic issue of receiving X11 on a Mac as Carl already alluded to.  So while you would in fact take care of the RGtk2 side (I maintain this as a Debian package r-cran-rgtk2) you are not yet all done.

**Comment by cboettig** [comment]
p.s. there are various alternatives to x-forwarding but all work on more-or-less the same principle. For instance, see: 

- http://stackoverflow.com/questions/16296753/can-you-run-gui-apps-in-a-docker-container 

 and in particular, see:

- http://stackoverflow.com/questions/25281992/alternatives-to-ssh-x11-forwarding-for-docker-containers/25334301#25334301

e.g. one can do:

```bash
docker run  -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:ro r-base
```
and now try: `plot(rnorm(10), rnorm(10)`

and yay, we have GUI / X11() output from inside a docker container, with no additional latency.  (on Linux; clearly a Mac-based host would need X11 first).  At least I should thank you for your question because I hadn't realized it was that easy before.

**Comment by znmeb** [comment]
I haven't actually gotten this to work - it's on my list of things to debug - but there are ways to serve up a VNC-like experience to a browser from a Docker container. See https://registry.hub.docker.com/u/mccahill/eclipse-novnc/ for one example.

**Comment by sje30** [comment]
Thanks everyone.

> ```bash
> docker run  -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:ro r-base
> ```

That didn't work for me on the mac.  I have X (via Xquartz) and tried a
few variants without success before reaching for the google wrench.
This thread and comment in particular

https://github.com/docker/docker/issues/8710#issuecomment-72669844

solved it for me.

i.e. 
    brew install socat
    brew cask install xquartz # SJE didn't need this step.
    open -a XQuartz

    socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\"

    # in another window
    docker run -e DISPLAY=192.168.59.3:0 -ti --rm r-base
    plot(1:10)


So... it should be possible, but replaces one set of problems
(specifically how to get RGtk2 working on mac) with a different problem
(e.g. installing socat and docker), but at least they are simpler
problems (to me at least).  THanks!

**Comment by cboettig** [comment]
Great, sounds like we're good here, so closing.  Thanks for the follow-up; perhaps we should add a page on the rocker wiki on this.
