### ISSUE TITLE
Version published docker images

### ISSUE THREAD

**Issue by maciej** [rocker-org/rocker#153]
Hi,

I was wondering if it would be possible to have stable versions (tags) of `rocker/r-base` (and other) images in Docker Hub?

My concern is that basing my Docker images on `rocker/r-base:latest` makes their build unstable, because the base image changes. This will almost for sure will result in incompatibilities down the road.

Thanks!

**Comment by cboettig** [comment]
Hi Maciej,

Good question.  Are you just looking for stable versions of R?  We could probably do that if we rewrote r-base to:

1.  base on a fixed debian flavor (e.g. Jesse instead of testing)
2. build R from source (and then clean-up to keep image size)

Currently r-base takes the more streamlined approach of installing from upstream debian:testing sources. However, this means that if we simply add tags to the existing infrastructure, you will then have a way to always get an image built from an identical Dockerfile, but the image itself would not be any more stable, since every time that Dockerfile rebuilt it would pull the latest available sources from the debian repos.  Does that make sense? Apologies if I'm rehashing what's obvious to you.

The strategy I outline above is common to many of the official Docker `library` images, but not all.  It does not, of course, guarantee that image remains completely unchanged, but rather permits the image to get the security updates that are released for older stable Debian flavors, usually without upgrading any existing versions of software unnecessarily.  (You could maintain a binary-identical snapshot of the r-base image, never rebuilt from source, if reproducing historical security vulnerabilities was important.)  

 So it would be good to be clear on what you mean by "base image changes", since the base image changes even when the Dockerfile does not change, and nothing guarantees you will not have incompatibilities down the road, though we could reduce those odds by building specific R versions on fixed releases.

**Comment by maciej** [comment]
Hi Carl,

Thank you for a quick response and sorry for not getting back to you earlier.

Let me take Docker's [Java repository][hub-java] as an example. If you look at its tags you can see that every release of OpenJDK is tagged with its exact version, and in addition to that you have tags for each major release, so for example `java:8` is now the same as `java:8u66`. The first of the two changes whenever a new version of Java 8 is released, the second, however, will always point to exactly the same image.

Now going back to `rocker/r-base` – would it be possible to have tags like `8u66` in Java's case. Those that would always point to the same image. These can be of any format: `R-version.build-version`, or timestamps: `YYYYmmdd`. In addition separate `r-base` might have separate tags that would point to an image containing the latest R version, latest stable version (like `java:8` in the Java example)…

I don't think this would require changing the Debian flavour, that's a separate thing altogether.

I hope it makes sense.

[hub-java]: https://hub.docker.com/r/library/java/tags/

**Comment by cboettig** [comment]
Hi Maiej,

I am afraid you are not following how Docker works.  The tag, e.g. java 8,
points to  a specific Dockerfile, as I explained before.  Please look at
the Repo information for the Java example, and you will see that a
specific, different Dockerfile is linked for each version.

**All the tag does is identify a unique Dockerfile**.  There is no magic in
Docker that is allowing tags to always build the same version.  That's
completely determined by what's in the Dockerfile. So, let us look at the
Java Dockerfile that corresponds to Java 8 tag:
https://github.com/docker-library/java/blob/200ecf22e5a23cb48cbb3ce47aa08aa3b49a0d2d/openjdk-8-jdk/Dockerfile#L16

There you see, on Line 16, this Dockerfile locks in a specific version.
Why does that work?  Well, look at the Dockerfile and you will see that
they build on a fixed version of Debian, (Jessie), not a floating version
(like Rocker, which builds on "testing" which is always the "current
testing branch").   Together, these lines mean that the commands on Lines
24-25 will always install the same version of R (from the Jessie repository
directly, since it's available there already, no need to build from
source).   Note also that the Java Dockerfile adds "backports" so they can
get security updates even when Jessie is no longer current, and note that
this Dockerfile would eventually break if it was not based on Jessie but
based on testing; since future testing versions will not always ship the
old versions.

So as I have already explained, the trick to making this work has very
little to do with Docker tags and actually requires writing the Dockerfile
differently than it is currently, as I have already explained.  Does this
make sense now?

On Thu, Dec 17, 2015 at 8:33 AM Maciej Biłas <notifications@github.com>
wrote:

> Hi Carl,
>
> Thank you for a quick response and sorry for not getting back to you
> earlier.
>
> Let me take Docker's Java repository
> <https://hub.docker.com/r/library/java/tags/> as an example. If you look
> at its tags you can see that every release of OpenJDK is tagged with its
> exact version, and in addition to that you have tags for each major
> release, so for example java:8 is now the same as java:8u66. The first of
> the two changes whenever a new version of Java 8 is released, the second,
> however, will always point to exactly the same image.
>
> Now going back to rocker/r-base – would it be possible to have tags like
> 8u66 in Java's case. Those that would always point to the same image.
> These can be of any format: R-version.build-version, or timestamps:
> YYYYmmdd. In addition separate r-base might have separate tags that would
> point to an image containing the latest R version, latest stable version
> (like java:8 in the Java example)…
>
> I don't think this would require changing the Debian flavour, that's a
> separate thing altogether.
>
> I hope it makes sense.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rocker-org/rocker/issues/153#issuecomment-165502561>.
>
-- 

http://carlboettiger.info

**Comment by maciej** [comment]
I think I can't agree with you regarding tags. The Docker documentation says that [tags are applied to images, not Dockerfiles](https://docs.docker.com/engine/reference/commandline/tag/).

I'm not a Docker expert, but my usual workflow looks pretty much like this:

```sh
docker build -t maciejb/project:latest .
# Now if I want to apply another tag to the same image I'd call:
docker tag maciejb/project:latest maciejb/project:another-tag
# Here I push the image and associated tags:
docker push maciejb/project:latest
docker push maciejb/project:another-tag
```

I can call `build` on the same Dockerfile more than once resulting (possibly) in different images and apply different tags to each of those images.

**Comment by eddelbuettel** [comment]
And we give you that:

```
edd@max:~$ docker images | grep ^r-base
r-base                       latest                cf4383562b44        3 weeks ago         1.014 GB
r-base                       3.2.2                 d8d772db8b82        9 weeks ago         998.9 MB
r-base                       3.2.1                 38a6a6b62751        5 months ago        563.5 MB
r-base                       3.2.0                 c09b226d89bc        6 months ago        551.6 MB
r-base                       3.1.3                 8a0dd612a7f5        9 months ago        516.7 MB
r-base                       3.1.2                 c04052b3ddd2        9 months ago        483.5 MB
edd@max:~$ 
```

I am closing this.  We explained this issue before; we are content with our workflow and so is Docker in blessing our `r-base` images (for which the PR for R 3.2.3 is pending).

**Comment by maciej** [comment]
:+1:

**Comment by cboettig** [comment]
Just for the record, all names, with or without tags, are applied to
images.  If you don't rebuild, the image doesn't change, regardless of what
you have tagged or not tagged (in fact, in this context the word 'tag'
means the name you give the image with the -t flag on build, which could be
any string and has nothing to do with the :tag).

Official images are rebuilt from dockerfiles just as I described.

On Mon, Dec 28, 2015, 4:58 AM Maciej Biłas <notifications@github.com> wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rocker-org/rocker/issues/153#issuecomment-167564500>.
>
-- 

http://carlboettiger.info
