### ISSUE TITLE
Alternate Debian repository? (http://debian-r.debian.net appears to be down)

### ISSUE THREAD

**Issue by dbuijs** [rocker-org/rocker#154]
I tried to add an SSH client to the rocker/ropensci image (with my own Dockerfile) and got the following errors:

    W: Failed to fetch http://debian-r.debian.net/debian-r/dists/unstable/main/source/Sources  404  Not    Found

    W: Failed to fetch http://debian-r.debian.net/debian-r/dists/unstable/main/binary-amd64/Packages  404  Not Found

    E: Some index files failed to download. They have been ignored, or old ones used instead.

It looks like http://debian-r.debian.net is down. It says it's a temporary outage, but it also says it went down Oct 20. I don't suppose anyone knows if there's an alternate repository I can use with this image to add `openssh-client`?

**Comment by cboettig** [comment]
Correct, Don's repo down, and at this time I don't believe there's a comprehensive alternative; though for most packages it is straight forward to just build from source anyhow (sometimes after installing a necessary library).  

Meanwhile, we've actually dropped that repo from more recent versions of rocker/hadleyverse and rocker/ropensci, so if you pull more recent versions of the `rocker/ropensci` image I think you shouldn't be still seeing that error.  `openssh-client` is in the standard debian repos, so you should be able to just apt-get that without a problem anyhow.

**Comment by dbuijs** [comment]
Doing `docker pull rocker/ropensci:latest` fixed it. Thanks.

I have my own Dockerfile that starts from rocker/ropensci:latest. I thought that every time I rebuilt it, it was checking Dockerhub for a more recent image. I guess it wasn't.

Thanks again. You helped me fix a bug I didn't even know I had.

**Comment by cboettig** [comment]
Glad it helped.  Yeah, that's an easy mistake to make; though if you configure "Automatic Builds" on Docker Hub for your Dockerfile, the Hub does always use the latest version of the FROM image, and you can pull your updated image from the Hub. (though of course I suppose there are reasons to prefer building your own image locally rather than let the Hub do it...)

Also for Automatic Builds You'll find there's an option under "Build Settings" to set "Repository Links".  You can enter the name of another Docker Hub image there, and this will cause your image to be updated whenever the FROM dependency is updated.  We use this to make sure changes in our base images always cascade through our stack.

**Comment by dbuijs** [comment]
Mostly, I'm still learning Docker and don't want to confuse others by posting a public Dockerfile that I'm probably not able to support. Although the possibility of automatic builds is making me reconsider this. 

For the time being, I will just make sure I pull the image before building locally.

FYI: The reason I wanted to add openssh-client is so that I can push my RStudio projects to github with SSH authentication. I generated the keys outside the container, but I still need the SSH client inside the container to handle the connection with github using the keys. This became a priority for me when I turned on 2-factor authentication for github. Others may also be interested in having the ssh client added to the image.

**Comment by cboettig** [comment]
Yup, that's a valid reason.  Actually `ssh` is now already on `hadleyverse` images, so you should be able to use git over ssh already on that or the ropensci image without installing anything else.

Note that you can actually still use https instead of ssh after enabling OAuth -- you simply need to create a GitHub personal auth token (PAT) and use that in place of your password when authenticating over SSH.  This can be convenient when you need to pull/push from GitHub on a docker instance running on some cloud server where you don't want to be copying your private key around.

**Comment by dbuijs** [comment]
And with that, you've already addressed the issue that started me on this whole adventure in the first place :)

I tried using an OAuth token, but couldn't figure out how to get RStudio to remember it. I'm essentially using the SSH keys the same way, generating keys only for this instance of the Docker container and registering them with GitHub (and nowhere else). When I destroy the instance, I'll dump the keys from GitHub. The finer grained access controls on OAtuh tokens are more appropriate for this though, so maybe I'll see if there's a way to store a token in a .profile file someplace.

Thanks again, both for this awesome Docker image and for your help on my non-issue that you already solved before I knew it was an issue.
