### ISSUE TITLE
boot2docker -> docker-machine

### ISSUE THREAD

**Issue by BillMills** [rocker-org/rocker#155]
`boot2docker` is now [toast](https://blog.docker.com/2015/08/docker-toolbox/), replaced by `docker-machine`; the instructions for finding the ip for the rstudio server [in the wiki](https://github.com/rocker-org/rocker/wiki/Using-the-RStudio-image) need updating. This works for me:

```
Bills-Air:rocker-intro billmills$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   ERRORS
default   *        virtualbox   Running   tcp://192.168.99.100:2376           
Bills-Air:rocker-intro billmills$ docker-machine ip default
192.168.99.100
```

**Comment by eddelbuettel** [comment]
The wiki being a wiki ... would you mind updating this?

Thanks!

**Comment by BillMills** [comment]
done - didn't want to mess with your wiki without talking about it first :)

**Comment by cboettig** [comment]
@BillMills Thanks!  @eddelbuettel and I don't see enough of the Windows/OSX side since it's not our native environment, but from what I have seen docker-toolbox has been a great step forward in streamlining the whole shebang there.  We could do with better documentation all the same, but community input on the wiki has been great so far.  

Would love to hear how your workshop went btw!

**Comment by BillMills** [comment]
Cool, I'll swing by the wiki again if I find any more bumps with docker-toolbox.

Haven't actually done the tutorial yet, it's 3.30 Pacific on Wednesday; the (probable) notes are [here](https://github.com/BillMills/Rocker-tutorial) and a live webcast link will be posted [here](https://github.com/minisciencegirl/studyGroup/issues/75) shortly before kickoff. Comments welcome! (but you're probably busy with the ropensci meeting atm, perhaps another time).
