### ISSUE TITLE
Question about saving data of multiple users using one rstudio docker instance

### ISSUE THREAD

**Issue by reyman** [rocker-org/rocker#160]
Hi,
On the [wiki page](https://github.com/rocker-org/rocker/wiki/Using-the-RStudio-image#multiple-users) of Rstudio image  your team says about multiple users : 

```
Note: you should not link any shared volumes to the host on a container in which you are configuring multiple users.
```

If i create multiples users (students, or other researcher which use rstudio) on this image, is there a way (different from shared volume) to save the data created by each users ? Is it possible to link these account created in docker image with `/home/folder` and posix user account stored in LDAP ?

**Comment by cboettig** [comment]
The wiki oversimplifies this a bit.  Just keep this in mind:

On the rocker container, you have the standard linux layout, so each user has a directory in `/home/username`.  You should feel free to link `/home/` to a shared volume with the host if that makes your life easier, but some care will be required (just to make sure users are all created with their permissions are configured correctly for their home directories, RStudio won't be able to log a user in if the user doesn't have and own their home directory).  

There are many alternatives as well, basically the things you would do in any remote environment, and a few extra docker ones (probably already obvious to you, but here we go):

- you can use `docker commit` to simply save the running container with all it's data (note: `commit` only captures data not in shared volumes) 
- you can use `docker cp` to copy data from the active container to the host machine.
- users can push data from the container to a third-party service (github, or install dropbox on the container, etc)
- install and run an ssh client or rsync on the container

The workflow for some of these is more tricky than others; e.g. if you want to install stuff on the running image you will want to first launch the image and then run `docker exec` to fiddle, or otherwise launch with `bash` instead of the default `supervisord` command, configure users appropriately, and go from there. 

HTH
