### ISSUE TITLE
Can't connect to docker based on image built from the Dockerfile 

### ISSUE THREAD

**Issue by jianlianggao** [rocker-org/rocker#176]
Hi,
   I downloaded the Dockerfile, run.sh, add-students.sh, userconf.sh to my Ubuntu14.04LTS and built a docker image based on the files. The build process was all right. But when I used docker run -d -p 8787:8787 <my own image name>. The docker started ok but couldn't be connected. While use docker run -d -p 8787:8787 rocker/rstudio to start a docker, there is no such a issue. Help please!
   Thanks,
J

**Comment by eddelbuettel** [comment]
Which Dockerfille? Ie which URL and repo?

Why did you not `docker pull ...` it?

**Comment by jianlianggao** [comment]
Thank you for reply.
   https://github.com/rocker-org/rocker/blob/master/rstudio/Dockerfile
 I am learning Docker, I am practising to build an image and mount with a docker container.
   Best regards,
J

**Comment by cboettig** [comment]
@jianlianggao Not sure I follow you.  First, can you confirm that you can connect to the RStudio docker container when you simply pull it, rather than building locally, following the directions on the wiki? https://github.com/rocker-org/rocker/wiki/Using-the-RStudio-image (I think that's what you mean by: 

> While use docker run -d -p 8787:8787 rocker/rstudio

but you haven't clarified if that is doing a fresh pull or if you named your local build `rocker/rstudio` as well.  Anyway, assuming that works, you say running:

```
docker run -d -p 8787:8787 . 
```

doesn't work.  I'm not sure what that's supposed to do, you haven't named an image.

If you clone this repo, `cd` into the `rstudio` directory, then:

```
docker build -t myrstudio .
docker run -d -p 8787:8787 myrstudio
```

Should work just as well as:

```
docker run -d -p 8787:8787 rocker/rstudio
```

If you were to  tell us the error message you get it might help.  For instance, if you have a previously running docker container on port 8787 already, then you cannot start a new one until you remove the old one (check `docker ps -a`).

**Comment by jianlianggao** [comment]
Sorry for confusing you. Let me clarify. First, I used the command line docker run -d -p 8787:8787 rocker/rstudio. A docker container (pulled from your github) ran properly. I could login to rstudio server using web browser. Then I was thinking to learn more about docker containers. I am trying to understand how to build my own rstudio server image and setup a running docker container based on my own built image. I didn't know where to start. I therefore visited your rstudio folder on github and found the files: Dockerfile, run.sh, add-students.sh, userconf.sh. I copied the files into my home folder and using docker build -t myrstudio:latest . to build my own image. When the image was built, I mounted onto a container using the command docker run -d -p 8787:8787 myrstudio. The container started successfully but just couldn't be connected from web browser. Hopefully I make me understood this time. Thank you very much.

**Comment by cboettig** [comment]
@jianlianggao you still haven't provided the error message, but sounds like you probably forgot to kill the previously running container instance on port 8787 as I already mentioned.  Please consult the official docker documentation and any of the excellent docker-for-beginners tutorials, stackoverflow and other forums for more information and reserve issues requests for possible problems that may need us to fix something on our end.

**Comment by jianlianggao** [comment]
@cboettig Hi Carl, there was no error messages during building image and run docker container. But just when using web browser to connect to the docker container by localhost:8787  , the browser always says the page can't be displayed. That was the only error message I had.
