### ISSUE TITLE
It's more a question than an issue

### ISSUE THREAD

**Issue by Black-Butterfly** [rocker-org/rocker#180]
Hi, 

I've tried rstudio and that work perfectly. It's more a question about possibilities ...

My case is : 

I have the rocker/rstudio containers and a own custom container with r-base 3.0.2-4.
I would like to know if it's possible to run rocker/rstudio with my r-base version and mostly how. I've tried with --link but I think I don't get how this option work. 

Even if we need the last version, some of our analysis use old version. This is why I ask if it's possible or do I have to create an own made rstudio container ? 

I just need that and everything will work smoothly ... 

I know, old r-base version is not your priority, but if you can help me to use my link container, to have my old version that would be just awesome. 

Sorry again for this question. I know it's more a docker question than rstudio one but it's quite both, so I though that you'll be the person that can give me the most accurate answer. 

Thank's in advance,

Regards.

In case, this is my dockerfile who work perfectly : 

[Dockerfile.txt](https://github.com/rocker-org/rocker/files/234480/Dockerfile.txt)

**Comment by cboettig** [comment]
For older r-base versions, see https://github.com/rocker-org/rocker-versioned

re linking, you can kind of make this work by sharing volumes, e.g. link the r-base $R_HOME (e.g. `/usr/lib/R`) to the $R_HOME location on rocker/rstudio (for some reason RStudio assumes this is always `/usr/lib/R and not `/usr/local/lib/R`), but this can be dodgy since other shared external libraries may be in different places or missing from the linked container (though they could be re-installed on the linked container).  Overall the rocker-versioned images will be a much simpler & more reliable way to run (recent) older versions of R along with packages from that period.
