### ISSUE TITLE
How about removing VOLUME command for Kitematic dependecny in rstudio Docker

### ISSUE THREAD

**Issue by teramonagi** [rocker-org/rocker#182]
I found that `VOLUME` command for Kitematic in rstudio Docker file.
- https://github.com/rocker-org/rocker/blob/master/rstudio/Dockerfile#L69

I try to use rstudio Docker file for my personal customize(`FROM rocker/rstudio` ... in my Docker file).
But, we don't do anything under `/home/rstudio/` directory once `VOLUME` command is run.

It means that we can not customize/touch .Rprofile file in /home/rstudio directory.
How about removing VOLUME command for Kitematic dependecny in rstudio Docker?

For example, `/myvol/greeing2` is not created after `docker build` in the following Dockerfile.
(Ofcourse, `/myvol/greeing` is created.)
```dockerfile
FROM ubuntu
RUN mkdir /myvol
RUN echo "hello world" > /myvol/greeting
VOLUME /myvol
RUN echo "hello world2" > /myvol/greeting2
```

**Comment by cboettig** [comment]
We encourage users to set the system .Rprofile like we do in the r-base image.  

It is better not to write to /home/rstudio since a user may want to share that volume to the host, as indicated by the use of VOLUME.  Does that make sense?  

(Also as you note, we use VOLUME so that kitematic users can still share with the host directory)

Perhaps we should use a of /home/rstudio instead.

Thanks for the issue, hope this helps and lemme know what you think!

**Comment by teramonagi** [comment]
I got it!!
I understand that I should write the setting in ```/etc/R/Rprofile.site``` as the following link says
- http://www.inside-r.org/r-doc/base/startup

Thank you for answering my question politely!

**Comment by eddelbuettel** [comment]
The `help(Startup)` page is a true treasure!
