### ISSUE TITLE
Some package installation freeze/unresponsive 

### ISSUE THREAD

**Issue by dominiqueemmanuel** [rocker-org/rocker#184]
Hi,

I try to install some packages in R in bash on my docker instance, and it freezes for some packages (and not for others).

For instance (in an R bash of my docker image : `sudo docker exec -it [my container] bash` then `R`), I try to launch this command:
`install.packages("ReporteRs")`

and it freezes (unresponsive -> I do not get back the R command line) just after the step
`** testing if installed package can be loaded`

I also tried 
`install.packages("ReporteRs",INSTALL_opts = "--no-test-load")`
and it freezes (unresponsive -> I do not get back the R command line) just after the step
`DONE (ReporteRs)`

Do you have any ideas or tips to solve this problem ?

Thanks very much,
Dom

**Comment by cboettig** [comment]
Installs fine for me (using rocker/hadleyverse image, since it has the java, libxml2 and so forth requirements already in place).  

The dependencies for that package look pretty heavy and several depend on external system requirements you will have to install by hand with apt-get.  However, the freezing is more likely do to your host system, but you haven't given us any details (as requested in [CONTRIBUTING](https://github.com/rocker-org/rocker/blob/master/CONTRIBUTING.md)) to help us debug.  My shot-in-the dark guess is that you're on virtualbox instance from docker toolbox, or otherwise a small instance and you are running out of memory during the install.

**Comment by dominiqueemmanuel** [comment]
Sorry for the incompteness of my request.

I'l try to complete my issue soon.

But your answer may already help me to investigate...

Thanks very much,
Dom
