### ISSUE TITLE
missing fonts for plotmath expressions

### ISSUE THREAD

**Issue by mnazarov** [rocker-org/rocker#204]
I discovered some fonts are missing when using `base-r`/`rstudio`/`shiny` images:
For example, large brackets (that are composed of 3 symbols) are not rendered correctly in a call like this:
`plot(rnorm(100), main = expression(bgroup("(", atop(x, y), ")")))`
![plot](https://cloud.githubusercontent.com/assets/2838666/20467176/d915fb6a-af81-11e6-85ee-a09838c7b621.png)
I wonder what package needs to be added to a docker container or if this is a different issue (encoding?)

**Comment by cboettig** [comment]
Thanks for the nice bug report.

I'm guessing they are some tex libraries; this should work in `rocker/verse` fine, though I reproduce this issue in `rocker/rstudio`.  Somewhat recently I've moved some of the tex libraries out of `rstudio` to downstream images like `verse` in order to keep a smaller base `rstudio` image.

**Comment by mnazarov** [comment]
Yes, it does work in `rocker/verse`, but I wanted to avoid blowing up the image with unnecessary stuff.
By some experimenting found that adding `gsfonts` solves this issue (and it is a fairly small addition).
But it is still unclear what is actually missing and which font/component from `gsfonts` helps.

**Comment by cboettig** [comment]
Nice, thanks, I'll add `gsfonts` in.
