### ISSUE TITLE
Docker image does not clean up session on "docker stop"

### ISSUE THREAD

**Issue by labkey-matthewb** [rocker-org/rocker#210]
If I use an attached volume the session is left in an inconsistent state when the image is stopped.   Running
> docker run -v `pwd`:/home/rstudio -P rocker/rstudio
and attach to the running server

> $ cat .rstudio/session-persistent-state 
> abend="1"
> active-client-id="62dbec4e-e518-42fb-abc1-9408fb4d046a"
> virtual-session-id="A38FD40C"

as expected abend=1.  However, after stopping the image abend is not reset

> $ docker stop {name} 
> $ cat .rstudio/session-persistent-state 
> abend="1"
> active-client-id="62dbec4e-e518-42fb-abc1-9408fb4d046a"
> virtual-session-id="A38FD40C"

I tried stopping the service via s6-svc or /etc/init.d/rstudio-server before stopping the container, but I could only seem to reset "abend=1" via the application menu (quit session)

expected behavior: using docker stop does a clean shutdown, not an "abend"

I'm not sure if the fix is to change how the docker images shuts down (using rstudio-server suspend-session before rstudio-server stop???), or changing how rstudio-server stop interacts with the rsession processes.

**Comment by cboettig** [comment]
Thanks for the bug report.  Looks like we need to include a `finish` script in our [s6 service directory](http://skarnet.org/software/s6/servicedir.html) so that `rstudio-server stop` gets run when the image is stopped.  

I've just added this now, https://github.com/rocker-org/rocker-versioned/blob/381761bde42ccc1957f025bf6a6ce117718eb4d2/rstudio/Dockerfile#L63-L65
, DockerHub should have the images built shortly.  

In my test this now sets `abend` to 0 in `/.rstudio/session-persistent-state`, but please test it out to make sure we're getting the behaviour you expect (I'd never poked around in `.rstudio/` dir before and may not be up to speed on this).  

Not sure if one would want any of the other [RStudio-server management](https://support.rstudio.com/hc/en-us/articles/200532327-Managing-the-Server) tools linked into s6; so far I've left the s6 config pretty vanilla.  (e.g. we could probably do more with logging; currently `docker log` is just showing the s6 log).  Definitely open to suggestions on configuration options.

**Comment by labkey-matthewb** [comment]
Thanks Carl.

**Comment by cboettig** [comment]
Closing since I think this is fixed. please re-open otherwise.

**Comment by labkey-matthewb** [comment]
This seems to work about 50% of the time.  I'm wondering if sometimes process 1 (s6-svscan) can exit before rsession finishes handling its shutdown chores.
