### ISSUE TITLE
Keep more versions of hadleyverse?

### ISSUE THREAD

**Issue by dfrankow** [rocker-org/rocker#212]
Thanks for your work on hadleyverse. I am new to docker, so feel free to advise.

I would like to make my own docker image from hadleyverse. I want to be able to update my software on a regular basis and build a new image. So far, every time I build, hadleyverse has shifted, requiring a 1G download for what may be small changes on my part.

I feel one way to solve this problem would be to depend on a particular version of hadleyverse if it hangs around for awhile (say, six months). Then, when I published a change, it would depend on images people already have.

Does that make sense? Could you keep more versions of hadleyverse around for this?

**Comment by cboettig** [comment]
Thanks for raising this issue, raises a few different things that you may want to keep in mind:

Short answer first: there's relatively little reason for you to update your own image just because Hadleyverse has changed upstream.  You can keep whatever version you currently have and build your downstream images on that.  (e.g. don't have your image on docker hub rebuild all the time, or build locally without pulling the newer hadleyverse).

More details:

- The images in the rocker stack, including hadleyverse, are all set to rebuild when their upstream image is rebuilt, or when (usually very minor) changes are made to that image.  As you've noted, rebuilding changes the layer hashes and so a Docker pull involves downloading all the layers a fresh.  

- Whenever the root image, `debian` is updated, all the rocker images are also updated. This happens every few weeks or so, as security updates are released for Debian. If you're running in a production environment, it's probably a good idea to always have these updates.  You can avoid downloading gigabytes each time by just not running `docker pull` but instead running `apt-get upgrade` on your instance; but I don't think it's in anyone's interest for us to host a bunch of images which haven't been rebuilt for months and lack these security patches.  

- As you note, the `hadleyverse` image has been updating somewhat more frequently than that.  This has been do to some recent active development and user-contributed changes to the upstream images (rstudio, tidyverse, verse etc).  As noted, these are usually small tweaks and do not mean you need to update your own image every time.  We've been in a more active development phase recently, but I expect these to taper off and changes will drop back to the more like every few weeks rate due to the Debian updates.  

- Speaking of versions, from your question I know what you mean (specific image hashes), but keep in mind the term "version" usually refers to the version of the software on the image, not the hash.  This is much more stable and multiple versions are already available, see https://github.com/rocker-org/rocker-versioned

- Side point: we're looking to deprecate `rocker/hadleyverse` in favor of `rocker/tidyverse`.  `tidyverse` is a good bit slimmer than `hadleyverse`, though lacking a `latex` suite (which is added in `verse`) and few other things that have always been in `hadleyverse` (e.g. java development env).  this would roughly cut the download size in half for you.  


Does this make sense?  Some of this is documented on the [rocker-versioned](https://github.com/rocker-org/rocker-versioned/blob/master/README.md) README but maybe we can make it more visible or better explained.

**Comment by dfrankow** [comment]
Thanks much for your detailed response. Not sure where else to chat, so:

- I don't know how to "keep whatever version you currently have and build your downstream images on that." I have a dockerfile that starts "FROM rocker/hadleyverse". I can add a tag or digest after, i.e. "FROM rocker/hadleyverse@something" but if I use the tag "3.3.1" it looks like that thing is not static, and if I add a digest, that will disappear quickly. So how do I keep the version I have? As a side note, I can't keep it on docker hub because it's internal to my company. So .. pull it and somehow push it into our internal docker hub?

- Thanks for the info on tidyverse. I actually want hadleyverse, as we use knitr to make docs. So, perhaps I will start depending on "rocker/verse" and see how that goes. That will stay, right?

Let me know if there is somewhere better to discuss this. Thanks again.

**Comment by cboettig** [comment]
Re keeping the image, as long as you don't run `docker pull rocker/hadleyverse` again on your local machine, your docker instance will have the old version of `hadleyverse`.  Any time you build your own image locally, it will use the version of `rocker/hadleyverse` already available locally unless you explicitly tell it to do otherwise, whether or not you add a digest.  

Of course you could run `docker save rocker/hadleyverse -o rocker/hadleyverse@something.tar` or whatever filename you wanted to save it as if you needed something more robust / portable.  Since you have a local docker hub at the company, you can also run `docker push` to push that binary to your local hub, just remember to keep the name rocker/hadleyverse (or change your FROM line accordingly).  Any of these approaches will leave you with a completely static/unchanging version.  

Still, I don't really recommend this route.  I don't run `docker pull` every time I build or launch an image based on `tidyverse`, but if I do I can just wait for the download (since that's usually on remote servers that have very fast internet connections anyhow).  Look at other official docker images and you'll see they do the same thing we do; e.g. both `mysql:5` and `mysql:8` images on Docker Hub were last built 3 weeks ago at current; same time `debian:jessie` was last rebuilt (to add security updates as I've mentioned).  Things should settle down soon on the `rocker` images too and rebuilds will be only every several weeks. 

Re tidyverse, if they're html docs, tidyverse is fine, but try out `verse` if you need pdfs.  `rocker/verse` isn't going anywhere any sooner than the rest of the suite; we'll do our best to see it maintained and stable.  (I won't delete `rocker/hadleyverse`, just trying to encourage people to shift to the newer images which I think are a bit more deliberately designed, now that `tidyverse` is a thing, and will be more actively maintained.)

Re discussion this thread is fine as far as I'm concerned.

**Comment by dfrankow** [comment]
Got it. Since we are biggish, we have a farm of servers that builds the docker images with jenkins, so it's pretty hard for me to control local cache on those machines. Sounds like if I want to fix the version, I'd have to push it to our local hub myself.

I want PDFs, so verse sounds like the one. You could just leave hadleyverse alone and make it depend on tidyverse (i.e. get rid of verse). That would leave all the people with hadleyverse out there happy. But, I can change to verse, too.

Thanks again for your attention.

**Comment by cboettig** [comment]
Hadley Wickham would like us to deprecate the use of his name to refer to his packages, in preference of the term tidyverse (see the tidyverse vignette if you are not familiar with it already).  Hence the new names.  Verse builds on tidyverse with additional software that isn't part of tidyverse.  Hope that provides some more context for the renaming.  Also, I've tried to keep hadleyverse relatively unchanged (though it now inherits from verse instead of rstudio).
