### ISSUE TITLE
Rstudio Docker with R3.2.1

### ISSUE THREAD

**Issue by pipemg** [rocker-org/rocker#220]
I can get a docker that contains Rstudio and R 3.2.1 because all are updated to 3.3 or in 3.1 and it crashes for some Bioconductor packages I need, Do you have one with that version?

**Comment by cboettig** [comment]
Should probably post this in https://github.com/rocker-org/rocker-versioned/issues since you're looking for a specific version.  As you can see, we don't have an rstudio-tagged image going back as far as 3.2.1, but we do have a base R at 3.2.0; and it should be easy enough to follow the Dockerfile recipe shown there to build rstudio on that instance.
