### ISSUE TITLE
Persisting changes

### ISSUE THREAD

**Issue by ashenkin** [rocker-org/rocker#228]
Hi all,

Thanks for this great resource.  I'm new to docker, but getting the hang of it bit by bit.  I've modded the dockerfiles to have rstudio-server running on R 3.0.2.  In order to install devtools (for install_version), I need to install libxml2-dev, which is fine.  However, in order to keep that persisted, I'm guessing I'll either have to add that to the dockerfile, or commit the container before killing it.  Is that correct?  I guess that's also why it's better to have shared directories for code rather than, say, pulling updated code from github directly into the container's filesystem...

Thanks,
Allie

**Comment by cboettig** [comment]
@ashenkin yes, writing a Dockerfile is the recommended way to ensure your installed software persists.

It's not clear what dockerfiles you're modifying, but sounds like you're doing something pretty similar to what is already in the `rocker-versioned` stack: https://github.com/rocker-org/rocker-versioned.  (e.g. you can specify R 3.0.2 by adjusting the Dockerfile in r-ver or just pass the R_VERSION as a `--build-arg` to `docker build`.  The subsequent Dockerfiles such as `rstudio` and `tidyverse` can also just have their `FROM` lines changed to use older R versions.  

As an aside, note that the images in `rocker-versioned` specify an MRAN snapshot repo rather than using `install_version` to install a specific version.  This is generally more robust than that `devtools` function, since the latter has no way of consistently installing the same version of dependencies of said package, while installing from MRAN means both that you can just use the standard `install.packages` and that the same version of all packages is always installed.

**Comment by cboettig** [comment]
Looks like this is resolved, closing.
