### ISSUE TITLE
R image using Alpine base

### ISSUE THREAD

**Issue by daveisfera** [rocker-org/rocker#231]
Alpine has become a popular base image because of its small size. Here's a Dockerfile that I made to build R using an Alpine base:
```
FROM alpine:3.5

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8

ENV R_BASE_VERSION 3.4.0

RUN apk add --no-cache bzip2-dev ca-certificates curl-dev pcre-dev perl readline-dev xz-dev zlib-dev autoconf automake gfortran \
    && apk add --no-cache libc-dev g++ make \
    && mkdir /tmp/build_r && cd /tmp/build_r \
    && apk add --no-cache curl \
    && curl -sSLO https://cran.rstudio.com/src/base/R-${R_BASE_VERSION:0:1}/R-${R_BASE_VERSION}.tar.gz \
    && tar xf R-${R_BASE_VERSION}.tar.gz && cd R-${R_BASE_VERSION} \
    && ./configure --build=$CBUILD --host=$CHOST --prefix=/usr --sysconfdir=/etc --mandir=/usr/share/man --localstatedir=/var --disable-java --without-x \
	&& make -j $(cat /proc/self/status | awk '$1 == "Cpus_allowed_list:" { print $2 }' | tr , '\n' | awk -F'-' '{ if (NF == 2) count += $2 - $1 + 1; else count += 1 } END { print count }') \
	&& make install \
    && rm -rf /tmp/build_r

CMD ["R"]
```

**Comment by eddelbuettel** [comment]
Cf #169 and #196

**Comment by cboettig** [comment]
Indeed it has. Here's another nicely maintained r-alpine based stack: https://github.com/artemklevtsov/r-alpine .

However, I've found that getting many R packages to build on a linux distro that's libc6 based instead of glibc to be a huge head-ache.  I've never been able to get RStudio to compile successfully on alpine.  And the resulting images are really not much smaller once you've pulled in a comparable package build environment to what we have on the debian based system.   So I don't see us moving in this direction for the time being.
