### ISSUE TITLE
ccache-usage

### ISSUE THREAD

**Issue by inkrement** [rocker-org/rocker#247]
I try to use packrat for each project, which makes it easy to create reproducable code. But one downside is that you have to compile/install each package for each project... which takes a lot of time. I was thinking of using ccache, which should speedup the process. Wouldn't it be nice if this docker-container uses it per default?

**Comment by eddelbuettel** [comment]
No, because we cannot possibly accommodate everybody's favourite package.  We try to provide a reasonable, and _small enough_, subset everybody can start from.  You can add `ccache` (which I personally love too and use on all machines) yourself.

Also note that for some people Docker itself plays the role of packrat.

**Comment by inkrement** [comment]
I understand that you just add some default-packages, but I wanted to suggest a completely different solution. Wouldn't it be possible to "wrap" the g++ and force the usage of ccache? I don't know how the compiler selection works in detail, but wouldn't it be enough to just set the CC, CPP environment variables to ccache g++? Another (quite dirty) way would be to directly link to /usr/lib/ccache/g++.

**Comment by inkrement** [comment]
oh, you were talking about ccache itself and not R-packages... sry, now i got it. I'll close this "issue" now.
