### ISSUE TITLE
Permission denied when using needs

### ISSUE THREAD

**Issue by moklick** [rocker-org/rocker#249]
Hey,

I started the container via:

`docker run -d -p 8787:8787 rocker/rstudio`

then I installed needs via:

`install.packages('needs')`

and use it:

`library(needs)`

When I confirm 'Yes', I get the following error:

```
Error: package or namespace load failed for ‘needs’:
 .onLoad failed in loadNamespace() for 'needs', details:
  call: file(file, ifelse(append, "a", "w"))
  error: cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '/usr/local/lib/R/etc/Rprofile.site': Permission denied
```

When I get the docs right the default user is always root. Can you help me with this?

**Comment by eddelbuettel** [comment]
That is a design bug in package needs which assumes it can write to that file, see eg [here](https://github.com/cran/needs/blob/master/R/needs-package.R#L32).  It looks like you can overcome that use case by setting an option.

It has nothing to do with rocker.

**Comment by moklick** [comment]
Thanks for the fast reply! I will check the needs options.

**Comment by truemoid** [comment]
@moklick did you resolve this?

**Comment by IntrovertHedgehog** [comment]
For anyone still frustrated with this error. This happens when `needs` want to autoload everytime it is used. To enable this, it has to modify `Rprofile.site`, which is usually located in `/etc/R/Rprofile.site`. You can also find where it is by following `'/usr/local/lib/R/etc/Rprofile.site'`, a symbolic link pointing to that profile.

Use these commands to allow write permission to all group:
```bash
cd /etc/R/
sudo chmod ugo+w Rprofile.site
```
