### ISSUE TITLE
Passing in default username/password is not recognized

### ISSUE THREAD

**Issue by jgbradley1** [rocker-org/rocker#255]
I am passing in the default username/password through the run command

`docker run -p 9000:8787 -e USER=rstudio -e PASSWORD=rstudio -e ROOT=TRUE rocker/rstudio`

however it takes me to the login screen. After entering the login information again, I think the browser caches the login info because it doesn't ask me to login again until after I've cleared the browser.

For an alternative approach, I built my own image (call it *myrstudio* )

```
FROM rocker/rstudio
ENV USER="rstudio" PASSWORD="rstudio" ROOT="TRUE"
```
and running `docker run -p 9000:8787 myrstudio` but I still see the same behavior.

Suggestions?

**Comment by cboettig** [comment]
Sorry, I cannot replicate any errors you describe using the above commands, they work as expected to me.  I would try just making sure that (a) you clear the cache first, and (b) just wait a second or two longer before trying to log in, so that the start-up script has time to run (though if rstudio-server is running, the script should be done...).  you can see the start-up script configuring the user here: https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/userconf.sh

Yes, RStudio-server will allow the browser to cache credentials, but this should not create any problems.  If you are already logged into the RStudio session, try logging out and logging back in.  You can of course clear the browser cache to forget the credentials.  

Simply changing the username you give in `-e USER=` will also bust the cached credentials and should just take you to the login page when you start a new docker instance.  

Not quite sure why you want to pass the default credentials explicitly, they work as such without being specified.  Of course you can specify unique pw/user combination that way.

Also not sure why you are testing a separate image, but yes, that should give identical results.

You might take a look at the logs and see if anything is amiss?  Here's an example of what I see:


```
docker run -p 8000:8787  -e PASSWORD=notrstudio -e ROOT=TRUE -e USER=notrstudio --rm rocker/rstudio
[fix-attrs.d] applying owners & permissions fixes...
[fix-attrs.d] 00-runscripts: applying... 
[fix-attrs.d] 00-runscripts: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] add: executing... 
Nothing additional to add
[cont-init.d] add: exited 0.
[cont-init.d] userconf: executing... 
USER is now notrstudio
Adding user `notrstudio' to group `sudo' ...
Adding user notrstudio to group sudo
Done.
notrstudio added to sudoers
[cont-init.d] userconf: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

Note the lines where the user is changed to my new user name, `notrstudio`, and is added to sudoers (since `ROOT=TRUE`), and `userconf` script is exiting with no errors (`exited -`).  

Sorry if I'm not following.  Just to be clear, if you simply run  `docker run -p 9000:8787 rocker/rstudio`, does everything work as expected?

**Comment by jgbradley1** [comment]
For my situation, I am trying to setup an image where the login screen is bypassed and users do not explicitly enter login credentials. I am able to grab login credentials automatically from somewhere else so there is no need to ask the user for their login creds again.

I was hoping that by passing in the login creds through an environment variable, the login screen would never show up.

**Comment by cboettig** [comment]
The config arguments you are using are for setting what the username and password are, not for filling them into the browser.  I don't think there's a way to do that such that users don't have to type in credentials, you'd have to talk to RStudio support though. AFAIK that's not supported in the open source edition of RStudio server. Maybe you could hack it by writing the credentials to the appropriate cache file in your browser's cache system, not that I recommend it.

**Comment by jgbradley1** [comment]
I understand. Thank you for the timely response. Rocker is doing some great work!
