### ISSUE TITLE
Wiki allows contributions/editing from non-contributing members

### ISSUE THREAD

**Issue by roribio** [rocker-org/rocker#256]
Hi,

I found your page on sharing files between Docker containers and hosts very useful. I decided to pull part of your page into my own wiki and inadvertently edited your page instead of mine.

My deepest apologies!

I have since reverted the changes I made but, I thought I'd bring the matter to your attention.

Best regards,
Ronald

**Comment by cboettig** [comment]
Thanks for the note; those settings are intentional as we do welcome wiki contributions from anyone.

Note that some of the details on volume sharing on Mac & Windows machines (as well as other references to Mac & Windows use in the wiki) may be somewhat dated to the old `boot2docker` days; nowadays linking volumes (and ports) on those platforms is I believe basically the same as on Linux with no special fuss.  Edits to this effect are welcome!

**Comment by roribio** [comment]
Noted! 

I have tried applying these settings on Mac running the latest Docker and macOS versions (17.06.0-ce-mac19 (18663) & Sierra 10.12.6 respectively). So far they've worked as advertised.

When I've tried mounting volumes on the Mac they get placed inside the Docker VM unless mapping to the /Users/... path.

**Comment by cboettig** [comment]
looks like this is resolved as a non-issue which I forgot to close!  

p.s. comments on the website documentation, https://rocker-project.org, also welcome!  Doesn't allow wiki-style edits, but PRs to the site (which is hosted on GitHub) are welcome!
