### ISSUE TITLE
addins not working?

### ISSUE THREAD

**Issue by ignacio82** [rocker-org/rocker#261]
I installed rocker/rstudio but I cannot get "Addins" to work. I get a grayed out window. My guess is that it has to do with [running RStudio with a proxy](https://support.rstudio.com/hc/en-us/articles/200552326-Running-RStudio-Server-with-a-Proxy), but I'm not sure if that is the issue nor how to solve it. Can you point me in the right direction?

Thanks,

Ignacio

**Comment by cboettig** [comment]
Hmm, addins work fine for me.  Please provide the information we request for new issues in [contributing](https://github.com/rocker-org/rocker/blob/master/CONTRIBUTING.md) guidelines (yeah, I get that the name is confusing), including the command you are using to run RStudio.  

Are you running your instance behind a proxy?  (though addins work fine for me with or without a proxy in front of the rstudio instance).

I ran:

```
docker run --rm -p 8787:8787 rocker/rstudio
```

then after logging in I did:

```r
install.packages("remotes")
remotes::install_github("rstudio/addinexamples")
```

Restart R from the session menu, and then I can add addins from the addin menu to an R script.

**Comment by ignacio82** [comment]
This is what I run:

    docker run -d -p 8787:8787 -e USER=<username> -e PASSWORD=<password> rocker/rstudio

I'm running the container on my synology nas

![screenshot 2017-09-22 at 2 21 19 pm](https://user-images.githubusercontent.com/1833309/30758790-c8de8fe4-9fa1-11e7-96f0-07fa02f54192.png)

**Comment by cboettig** [comment]
@ignacio82 Thanks for providing more information.  

You are not having a problem with RStudio addins, your issue is just about Docker and port sharing.  That's not the generic addin menu, that's specific to `blogdown:::new_post_addin`.  

Judging by the screenshot, you see that this particular addin is listening on `127.0.0.1:3643`.  You'll need to change the host address to `0.0.0.0:3643`, and then you need to bind the port `3643` when you run Docker, just like you are already binding the port `8787`.  To change to `0.0.0.0` you may have to investigate the blogdown documentation or contact the package maintainer.

**Comment by ignacio82** [comment]
I also have this problem when i try to run a shiny app from rstudio

![image](https://user-images.githubusercontent.com/1833309/30759597-d0d50cfc-9fa4-11e7-8ea2-c1233f8a1776.png)

**Comment by ignacio82** [comment]
After some trial and error it looks I can say that this has nothing to do with your container. If I login to using my local IP address, then everything works as expected. Alas, if I login using my domain name, all the shiny stuff does not work. No clue how to fix that, it probably has something to do with how my synology redirects the traffic :(

**Comment by ignacio82** [comment]
In case someone else is trying to use a synology, this solves the problem:
https://github.com/orobardet/dsm-reverse-proxy-websocket
