### ISSUE TITLE
auto-add all host users?

### ISSUE THREAD

**Issue by inkrement** [rocker-org/rocker#274]
Is it possible to directly add users on the docker-host or do I have to connect to the container and add all users a second time? I tried it, but `/etc/passwd` in the container does not contain the new users.

The problem is, that I want to add my users persistently. Furthermore, I am using docker-compose and there is nothing like a "pre-run-script-directive", which would allow to run some add-all-user script before running the service. So I would have to rewrite dockers run command (in the Dockerfile) and pre-run a loop which adds all users manually and then call the rstudio service, right?

**Comment by eddelbuettel** [comment]
Just thinking out loud here:  could you not switch to _external_ user management via something like NIS?

**Comment by cboettig** [comment]
also just brainstorming here: 

Since it sounds like you're using the rstudio-based images you could just put a bash script in `/etc/cont-init.d`; any script found there is run on startup before RStudio starts (and are how we modify the user settings that get passed in as env variables, e.g. see the example: https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/Dockerfile#L74.  (e.g. you could do this as a volume link: `-v .add_users.sh:/etc/cont-init.d` to link a local add-users script?)

Steph Locke has some notes related this (which use a .csv file and an R script instead to add users I think): https://itsalocke.com/blog/building-an-r-training-environment/

anyway, let us know what you think, maybe that's something we can streamline better.

**Comment by cboettig** [comment]
Oh, note if you do put your scripts in `/etc/cont-init.d`, you'll want to be sure to put:

```
#!/usr/bin/with-contenv bash
```

on the top, rather than the usual `!/bin/bash`.  an annoying gotcha due to s6 trying to be too clever.  (see the current examples in `userconf` and `add_shiny` scripts.

**Comment by inkrement** [comment]
Thanks for your input! I also thought of some sort of "more advanced" authentication before, but my first thought was LDAP and it seems like it is only available in the Pro-version. I'll close this issue for now and try to get NIS to work.

**Comment by zhqu1148980644** [comment]
NIS still doesn't work
