### ISSUE TITLE
Proposal to change base OS to alpine

### ISSUE THREAD

**Issue by jgbradley1** [rocker-org/rocker#275]
Would someone care to elaborate on why a debian-based image is used instead of a much smaller OS such as alpine? Is alpine not mature enough or are there other limitations I may not be thinking about?

**Comment by cboettig** [comment]
@jgbradley1 Sure; alpine is based on musl instead of glibc, which makes many common things (e.g. RStudio) difficult or impossible to compile.  Also, you may have noticed Dirk's is and has been the Debian maintainer for R for some two decades, so that's a lot of experience and expertise we all benefit from immensely by sticking to Debian.  

I think the difference in size is pretty illusory.  In my experimentation, once you start adding a fully functional R development environment the builds get pretty large regardless of OS (you've probably noticed most of the size of the Rocker images is not due to the size of the Debian base).  

You can already find some nice alpine-based Docker images with R from @artemklevtsov at https://github.com/artemklevtsov/r-alpine, though not sure how up-to-date they are (looks like issues on the hub builds).
