### ISSUE TITLE
Wrong tag version

### ISSUE THREAD

**Issue by slayer** [rocker-org/rocker#279]
```
$ docker run -it --rm r-base:3.4.3 R --version
R version 3.4.4 RC (2018-03-09 r74380) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

**Comment by eddelbuettel** [comment]
Indeed.  That crept in because the container rebuilt when I had already uploaded the 3.4.4 release candidate as 3.4.3.201803xx with whatever the date was.

@cboettig I guess that is a short coming of our code in 

```
ENV R_BASE_VERSION 3.4.4

## Now install R and littler, and create a link for littler in /usr/local/bin
## Also set a default CRAN repo, and make sure littler knows about it too
RUN apt-get update \
	&& apt-get install -t unstable -y --no-install-recommends \
		littler \
                r-cran-littler \
		r-base=${R_BASE_VERSION}* \
		r-base-dev=${R_BASE_VERSION}* \
		r-recommended=${R_BASE_VERSION}* \
```

Maybe we should remove the trailing star?  

And I guess for the r-base images that cannot be reverted easily.  But a) the difference between 3.4.3 and 3.4.4 is small, and we of course have the explicitly versioned rocker containers.

**Comment by cboettig** [comment]
@eddelbuettel  Good catch, your call on removing the trailing star to fix the version, maybe that's a good change. 

@slayer yeah, like Dirk says, you can always use `rocker/r-ver:3.4.3` to git the explicitly versioned container

**Comment by eddelbuettel** [comment]
I removed it.  That, given my versioning scheme for the Debian package r-base, should prevent a repeat.

@slayer Thanks a bunch for the heads up.  That will make things better.  Sorry about having r-base:3.4.3 slip a little towards 3.4.4.

**Comment by eddelbuettel** [comment]
Needed two passes -- the winning form is `${R_BASE_VERSION}-* ` as we need the hyphen to prevent the pre-release version 3.4.3.20180320 to creep in, yet we need the * to allow 3.4.3-1, 3.4.3-2 etc pp.
