### ISSUE TITLE
R 3.3.2 Docker image is actually 3.3.3 RC?

### ISSUE THREAD

**Issue by animedbz16** [rocker-org/rocker#282]
Seems like the Docker tag for 3.3.2 was overwritten for some reason?

```
[user@localhost r]$ docker run -it r-base:3.3.2

R version 3.3.3 RC (2017-02-27 r72279) -- "Another Canoe"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> 
```

**Comment by eddelbuettel** [comment]
Same thing happened with R 3.4.4 (cf #279) #but we since tightened the regexp so that only the (Debian package release numbers) a.b.c-version will be matched, and not the test builds a.b.c.yyyymmdd-version builds of the next 'c+1' version.   

That was my bad, but there is fairly little we can do now, particularly at the Docker hub.   If you truly need R 3.3.2, you can use either the sources and build, or the Debian binaries from the [snapshot archive page for r-base](http://snapshot.debian.org/package/r-base/).  You could use the latter too to cook up a new Docker container if you need one.  

So in sum I think we should close this.

**Comment by animedbz16** [comment]
This thread here seems to indicate that DockerHub will delete tags via support request (https://github.com/docker/hub-feedback/issues/368#issuecomment-147577966)

Not sure if they still do that or not, but could be worth an inquiry to allow you to rebuild those images correctly.

**Comment by eddelbuettel** [comment]
That's a little hypothetical as I don't have or interest to chase this.    The versioned build is a free service, we do what we can but there is a limit.  

Sorry.

**Comment by animedbz16** [comment]
Understood, just wanted to pass along the issue since I crept up against this looking at some older stuff and wanted to pull down this specific version quickly in a docker environment.

**Comment by eddelbuettel** [comment]
Appreciate the understanding.  I am in no small part frustrated by the actual issue -- I was kinda nice to have a sequence of 'tagged' r-base builds and we had this going for a few years.   Sadly, I messed up so we are missing a few.  

Hopefully it should be better going forward.

**Comment by cboettig** [comment]
@animedbz16 you've may already be aware, but we have separate stack for versioned tags in https://github.com/rocker-org/rocker-versioned, e.g. you can use `rocker/r-ver:3.3.2`.  

As outlined in the README, that stack takes a slightly different approach building on `debian:stable` which has some advantages and some disadvantages, but might suit your current needs.

**Comment by animedbz16** [comment]
@cboettig Thanks for the tip, I think that may work for my needs.
