### ISSUE TITLE
Not able to access installed rust

### ISSUE THREAD

**Issue by sumandoc** [rocker-org/rocker#288]
Hi there, 

I am trying to build a docker image to use as a development environment for building R packages that enables to include [rust](https://www.rust-lang.org/en-US/) code. This is [the image](https://github.com/sumandoc/P6RStudio) with its [dockerfile](https://github.com/sumandoc/P6RStudio/blob/master/Dockerfile).

I successfully install the rust in this image with this command:
```bash
curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
```
which installs binary to `/root/.cargo/bin`.

I try to append this folder to $PATH as:

```
ENV PATH $PATH:/root/.cargo/bin
```

Everything goes fine but still I am unable to access rust from terminal.
I thought it could be due to permission issues. So consulted [this issue](https://github.com/rocker-org/rocker/issues/246) but still I could not solve it.

What is the way around for this?

**Comment by cboettig** [comment]
Yeah, looks like that would create a permission issue.  You've installed it as root I'm guessing you're not running as root when you are trying to access rust?   The simple thing would just be to change ownership or group of `/root/.cargo/bin`:

```
chown root:staff /root/.cargo/bin
```

(The default user, `rstudio` is a member of the `staff` group, this should give that owner permission to execute the rust binaries).  

It also might be more conventional to put the binaries in `/usr/local/bin` than in the default `/root/.cargo/bin`.  Note that the `r-base` images this is all a bit easier since you can `apt-get install cargo` from `debian:testing`.  It might be worth us adding `rust` to `rocker/verse` to streamline this in the rstudio stack as R + `rust` becomes more popular...

**Comment by eddelbuettel** [comment]
I am not sure what why you think we can help you.  (Aside from reminding you that the `rust` compiler is in fact in Debian too so you could extend our container.)  We are not responsible for their toolchain.  

I would start with `apt-get`, initially interactively.

**Comment by sumandoc** [comment]
Thanks @cboettig for your assistance.

 Even after changing ownership 

```
chown root:staff /root/.cargo/bin
```
I am not able to access `rust` from the terminal.

I tried two things after that:

1. Move the binaries  `mv /root/.cargo/bin/* /usr/local/bin/`

2. Create symlink `ln -s /root/.cargo/bin/* /usr/local/bin/*`

Still with these two manuevres I could not access it.

This is the [minimal docker image](https://github.com/sumandoc/rust-rstudio/blob/master/Dockerfile) I created just for that.

**Comment by cboettig** [comment]
@sumandoc But in your minimal example you have now stopped adding `/root/.cargo/bin` to your `$PATH` .  (Also in your minimal example you seem to be attempting to `chown` files in `/root` after you moved them somewhere else).  Put your move command at the end and then:

```
docker build -t test
docker run --rm -ti -u rstudio test which rustc
```
seems to work fine.  Looks like you probably want to do

```
docker run --rm -ti -u rstudio test rustup install stable
```

to get some default toolchain built. Anyway, I suggest going for stackoverflow since these are general linux, rust, or docker questions and you'll get better support there.  These issue threads are really for bug reports or problems particular to rocker images.

**Comment by sumandoc** [comment]
@eddelbuettel Thanks for suggestion.

I successfully installed `imagemagick` via `apt-get` in `rocker/tidyverse` but I am unable to access it  within rstudio-server terminal. What could be the possibility?

**Comment by eddelbuettel** [comment]
@sumandoc Don't put random question into unrelated tickets. Always provide a minimally reproducible example and "am unable to access" describes too little to be actionable. 

In any event, we are not here as a generic Docker helpline.

**Comment by sumandoc** [comment]
@eddelbuettel I don't mean asking "generic Docker question" rather I meant **extending** the `rocker` container. I thought it would be redundant to open new ticket for issue where the problem boils down to extending the container (same thing).

I want to extend the existing container to include `imagemagick` via `apt-get`. As per your suggestion I should be able to use it within `rstudio`.

This is how I extended the image: **MWE**

```
FROM rocker/tidyverse
RUN apt-get update && apt-get install -y imagemagick 
```
As I am not able to use it, I am seeking help.

**Comment by eddelbuettel** [comment]
I am locking this thread now.
