### ISSUE TITLE
[Feature Request] Tidyverse + rstan

### ISSUE THREAD

**Issue by alexhallam** [rocker-org/rocker#293]
Is there a chance that you will make a tidyverse + [rstan](https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Mac-or-Linux) image?

**Comment by cboettig** [comment]
@alexhallam good question, that's come up before as well.  Could you provide a bit more detail about the relevant issues?  I'm not very experienced with STAN.   It seems like `rstan` already installs just fine out of the box on the existing images; we tend to focus extensions on bits like geospatial where there's quite a number of potentially tricky system libraries that need to be installed first.  Certainly building it in would side-step the issue of compile time.  

Related issue is whether we should have a more general Bayesian image; in particular there's quite a range of packages in this area, e.g. `greta`, `nimble`, as well as older stuff like`jags`, though I imagine most users tend to stick with a single one of those.  The case for something like `greta` might be more compelling since the docker image could bake in the Tensorflow / GPU support stuff, though that would be more at home in our nascent [ml](https://github.com/rocker-org/ml) images.  Clearly I'm just spitballing ideas here.

Anyway, thanks for getting in touch and will leave this open for the moment for any further discussion.  Thoughts/feedback welcome.

**Comment by mavelli** [comment]
because i need it too, i created one some time ago:
https://github.com/mavelli/rocker-bayesian
also on dockerhub
it has a bit more than rstan in it and can be used for teaching bayesian tools to colleagues too

**Comment by alexhallam** [comment]
## Issue With Current Image

@cboettig  I think the only non-standard step in installing `rstan` is making and configuring a `Makevars` file with the following contents.

```r
dotR <- file.path(Sys.getenv("HOME"), ".R")
if (!file.exists(dotR)) dir.create(dotR)
MAKEVARS <- file.path(dotR, "Makevars")
if (!file.exists(MAKEVARS)) file.create(MAKEVARS)

cat(
  "\nCXXFLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined",
  file = MAKEVARS, 
  sep = "\n", 
  append = TRUE
)
```
I have not had an issue with this due to your image. My issue is that I am running into memory issues on my server during the install. 

In my experience `rstan` takes relatively longer to install than other packages and requires more resources. My install freezes during install due to memory --- this is a known issue. Normally, I would just temporailly upgrade servers. This would be fine if I was using AWS, but with the current service I am using I pay monthly for a cheap server which works fine until I need to do a memory hungry install. I only mention all of this because there could be others in this same situation. I don't know much about docker, but I used to have a memory issue also when installing the equivalent of `rocker/tidyverse` your docker image fixed that problem. 

Also, there is a "stack" of sorts that is associated with bayesian analysis. It would be convenient to have this stack loaded on an image.

## Tidy Bayes Stack

If I were to make a wish list I would have the following

`rstan` - R interface to stan ([here](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started))

`brms` - My prefered modeling library. Advanced bayesian modeling with syntax similar to lme4 ([here](https://github.com/paul-buerkner/brms))

`bayesplot` - usefull for analysis of MCMC chains ([here](https://github.com/stan-dev/bayesplot))

`tidybayes` - Stan's output does not come in nice tibbles. tidybayes is the solution to this problem and interfaces well with `rstan`, `rstanarm`, and `brms`. ([here](https://github.com/mjskay/tidybayes))

## Other resources

1. Examples of various modeling via `brms`, `tidyverse`, and `ggplot` based off of "Statistcal Rethinking". ([here](https://github.com/ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse))

2. Example of using `tidybayes` + `brms`+ and similar packages in modeling. ([here](http://mjskay.github.io/tidybayes/articles/tidy-brms.html))


Also, thanks @mavelli for linking to your image. I think it is usefull for bayesian modelers loking for a JAGs stack.

**Comment by cboettig** [comment]
@mavelli Thanks for sharing your example!  We love seeing examples "extending" the rocker stack for particular domain applications, particularly when they are maintained by experts in that domain, and we hope rocker makes this easier to do (feedback on that welcome).  Such a distributed community approach is certainly more effective than trying to do everything in rocker.  I think we'd be happy to link to a collection of such images on our READMEs and https://rocker-project.org if you like.  

@alexhallam Thanks for the detailed reply.  Having a derivative image prebuild on DockerHub like @mavelli does should bi-pass the issues of compile time+memory, and maybe Damir would entertain your suggestion to add some of those additional packages like `brms` on his build.

**Comment by mavelli** [comment]
@cboettig sure, you can link to the image. actually i am also running my own GIS extension in a similar way but since you are having an "official" rocker GIS image, i didnt publish it anywhere yet - it being quite similar to yours.
i looked at your build system and versioning... now my image is not versioned. is there a good practice guide how to integrate extension-images like rocker-bayesian into your versioned rockerverse? any input/feedback/critique welcome

@alexhallam great input! recently i started rethinking how i code and go more towards tidyverse - so i will extend the rocker-bayesian with the packages you suggested for a tidy bayes stack here. the building takes long (hours) because of the compilations of jags and stuff, but once it is through, i would love to get feedback from you if everything is in you need as a toolchain

**Comment by cboettig** [comment]
@mavelli not at this time, though we should add something like that (https://github.com/rocker-org/rocker/issues/293).  Meanwhile, yeah, hopefully the [rocker/geospatial](https://github.com/rocker-org/geospatial) is something of an example template.  

Versioning is simple, if relatively manual: a different directory for each R version, identical Dockerfile except for the `FROM` line indicating the version up stream (identical unless you have packages not available on older versions).   In Docker Hub you can point to each sub-directory like so:

<img width="1233" alt="screen shot 2018-07-04 at 1 04 32 pm" src="https://user-images.githubusercontent.com/222586/42292952-2f12df08-7f8b-11e8-987f-9503332c420e.png">

You might choose to version only minor versions (`3.4`, `3.5`) rather than patch versions.  (Most of the stack supports these out of the box, `rocker/verse:3.4` automatically resolves to `3.4.4`, though geospatial hasn't added this feature).  

CRAN packages will automatically obey the timestamp set by the version (thanks MRAN snapshots).  Installations from GitHub can be manually pinned to a 'tag', I think there's no easy way to pin versions to a generic cran-like repo, though `devtools::install_version` might help if the repo maintains archives.


There's other very minor niceties (e.g. note that `install2.r` supports the flags `--repos` and `--dep`, no need for manual `install.packages()`, convention is to list apt-get dependencies on separate lines alphabetically for easy maintenance)  but really your image looks great!

**Comment by mavelli** [comment]
i updated now rocker-bayesian - it should be ready in 4-5 hours on dockerhub

@cboettig thank you! i also cleaned up the Dockerfile with your suggestions. i actually didnt know you can pass repo directly to install2.r - sweet!
Versioning.. manual copy-pasting .. since i am not using old versions, i could just set up the Dockerfiles and automatic build in dockerhub, but i would not be testing it. sounds sensible to have the minor version tags at least for >=3.3.

**Comment by mavelli** [comment]
verse has tex and publishing tools added to tidyverse

**Comment by eddelbuettel** [comment]
Can we close this?
