### ISSUE TITLE
rocker/rstudio:3.5.1 still using install.packages snapshot from July 2

### ISSUE THREAD

**Issue by lshep** [rocker-org/rocker#304]
I have pulled the snapshot rocker/rstudio:3.5.1 and when I install packages it is still grabbing a snapshot date of CRAN from July 2 
```
trying URL 'https://mran.microsoft.com/snapshot/2018-07-02
```
It seems like at the least from the mran.microsoft.com FAQ section the snapshot should be Aug 1 if not getting the latest CRAN builds.  Why is it so out of date?

**Comment by cboettig** [comment]
@lshep yup, if you want the `latest` CRAN builds, please use the `latest` tag.  It's arguably a good point that `3.5.1` should be identical to latest, but to reduce the burden on hub auto-builds we re-build  the tagged versions only monthly.  That said, it should have rebuilt Aug 1 but for me messing up a post-build hook (which moves the minor tag so that `3.5` points at `3.5.1`), so thanks for the report and will be fixed soon.

**Comment by cboettig** [comment]
fixed
