### ISSUE TITLE
How to best deal with user permissions in directories mounted with -v

### ISSUE THREAD

**Issue by boulund** [rocker-org/rocker#324]
I'm a bit confused regarding how to best handle user permissions in directories mounted with the `-v <host_dir>:<dir_inside_container>` argument to `docker run`. I saw a previous issue about this, https://github.com/rocker-org/rocker/issues/50, but it was closed so I figured I could open a new issue to discuss this. 

I'm mostly used to working with CLI applications in Docker and there it's been working fine for me to use `-u UID:GID` to set user and group id for files created when working in the container in combination with folders linked into the container with `-v /path/to/my/input/data:/input`. 

Maybe my situation is a bit uncommon, but we're planning to run a Docker image based on `rocker/tidyverse` on a server where we have a shared folder where we keep all common project files, input data, results, analysis files, etc. This folder is located outside of our home folder (it's a pseudo-account located in its own home folder). The top-level shared folder is owned by root and a shared group. Files in this folder are created using a umask of 002, and since the top-level shared folder has sticky group permissions this means all files and folders are owned by the account that created the file/folder and the shared group. 

What I'd like to do is to link this folder to a mirrored folder inside the container, i.e. `-v /sharedfolder:/sharedfolder`, and be able to access that folder inside RStudio. However, running for example `docker run -it -u $(id -u):$(id -g) -e PASSWORD=hello rocker/tidyverse` leads to:

```
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
```

I have a feeling this is expected, as the user ID I supplied on the command line most likely won't have permissions to execute the startup scripts. 

It seems to me that the suggestion in https://github.com/rocker-org/rocker/issues/50 is to mount the folder into `/home/rstudio/sharedfolder` without giving a user and group to docker using `-u` , but that doesn't seem to do what I want. I appear to be unable to create files or folders in the mounted folder `/home/rstudio/sharedfolder`. While I realize this might mostly be a Docker-related issue and not so much a rocker/tidyverse thing, I would really appreciate some advice on how to best deal with this type of situation.

**Comment by cboettig** [comment]
The default command on `rocker/tidyverse` is `init`, which launches the s6 init system that both handles startup configuration (like setting custom password provided as an environmental variable) and then bringing up the RStudio server.  As you guessed, these need to be run as root, so you cannot run `rocker/tidyverse` with a `-u` flag or you will get the permission error shown.  

If you are not using RStudio, you can always run these containers with a different command, e.g. `docker run --rm -v /sharedfolder:/sharedfolder -ti -u $(id -u):$(id -g)  rocker/tidyverse bash` to start a bash shell etc.  If each user is running docker individually and you're not using RStudio, this is the way to go.  

If you instead want your users to log in with their own passwords via RStudio Server, everything should work just fine as you outline it if you simply link volumes and let `rocker/tidyverse` run as root with it's default command.  link volumes with `-v`, and create new users on the container either manually (e.g. `docker exec` into the container after it is up) or add a startup script to the `init` system which will add all the users.  As long as each user is added to the same GID as well, and you ensure the GID on the host matches the GID inside the container, these users should be able to access and modify the shared folder no problem.  (This can be nice if your users don't have `docker` group permissions and prefer an RStudio-based interface instead of ssh+bash; though of course you can add an ssh server and have them ssh directly into the container instead of using RStudio too).  

HTH!

**Comment by cboettig** [comment]
Certainly, that works too.  If you are sharing volumes, you still only to
ensure that the user on the container (ie the default user, rstudio), is
added to the right GID for the shared group.  You can do this with an
additional init script or via a Dockerfile extension.

-- 
---
Carl Boettiger
http://carlboettiger.info/

**Comment by boulund** [comment]
Nice idea! That should work just fine. I'll just add a startup script that adds the rstudio user to the requested group!

**Comment by boulund** [comment]
I read up a bit on the s6 init system and had a look at the init scripts in `/etc/cont-init.d`, specifically `/etc/cont-init.d/userconf`. It seems the functionality I was interested in is already implemented through that script! 

So, the solution is to start the container with `-e USERID=<userid>` and `-e GROUPID=<groupid>`. The `userconf` init script will then recreate an `rstudio` user with the correct user and group IDs when launching the container. Neat. If combined with `-v <host_path>:<path_in_container>` this works well to read, edit, and create files on the host using the correct permissions. 

Thanks for the help leading me to find this @cboettig!
