### ISSUE TITLE
Updated Rocker Images - Error Ocurred During Transmission

### ISSUE THREAD

**Issue by davisidarta** [rocker-org/rocker#338]
Hello there, rocker team! I love your images and I use them extensevily.

I've just updated the rocker/tidyverse image, in order to try the new R 3.6 features (I've checked your docker hub and your images have been recently updated). However, when I try to run Rstudio server or rocker/tidyverse (my usual choice), I get an error output after the login panel: 

![image](https://user-images.githubusercontent.com/44589562/57097642-9d626b80-6cee-11e9-9a86-ef595e700062.png)

I haven't changed anything else on my system and the image was working perfectly before the update, so I'm assuming that's whats causing it. 

Here's some info on my running system:
Ubuntu 18.04.10 LTS
Docker version 18.09.3, build 774a1f4

**Comment by cboettig** [comment]
@davisidarta thanks for the kind words!

You're right that we just posted the `3.6.0` images (a bit behind release this time, apologies for the delay), but actually those images haven't even built on hub yet (takes about ~24 hrs before the nightly trigger hits and they build).  You can verify the version by including it in the tag, e.g. if you do `docker pull `rocker/tidyverse:3.5.3` you'll probably get the same image you have, and at the time of writing this, `rocker/tidyverse:3.6.0` will throw an error.

Have you tried just refreshing the browser page?  This error is usually just what it says on the tin and a refresh will fix it.  Otherwise, are you linking local volumes? Sometimes stuff left over in `.Rproj.user` from a previous session can cause issues; you can usually delete that hidden directly safely as it is just a temporary cache RStudio uses for things like restoring any open tabs and unsaved files etc)

**Comment by davisidarta** [comment]
Hello @cboettig! Thanks for clarifying! I've followed your advice and deleted .Rdata stored from my last session in the linked volume. This solved the problem. Thank you!
