### ISSUE TITLE
Can't connect rstudio to postgres database 

### ISSUE THREAD

**Issue by danalexandrucraciun** [rocker-org/rocker#346]
First of all I want to thank you for your hard work maintaining this. Your project saved me for a lot of issues. 
Unfortunately, I have a problem connecting the rstudio to a postgres db. I can do it through R, but not from connections tab within rstudio. 

I'm thinking there may be some other packages that need to be installed or ODBC sources/drivers. Does the container come prepared for this kind of connection? 

I look forward to receiving your reply. 

Thanks, 
Dan

**Comment by danalexandrucraciun** [comment]
the information that i have found on rstudio forums says: 
__________________________
I think what you need to do is connect to your Postgres via OBDC doing something like this:

db_connect <- function(){
    DBI::dbConnect(odbc::odbc(),
                          Driver       = "PostgreSQL",
                          servername   = "your_server",
                          database     = "dev",
                          UID          = keyringr::get_kc_account('redshift'),
                          PWD          = keyringr::decrypt_kc_pw('redshift'),
                          Port         = 5439)
}

Youll also want to make sure you have the correct odbc drivers installed on your machine in advance. Which you can get more information about here: https://db.rstudio.com/databases/postgresql 114 ... although this page kind of implies that what you are doing sould work, unless i'm missreading it?
___________________

**Comment by eddelbuettel** [comment]
RODBC was the first CRAN package I started to maintain for Debian ... around 2002.  But ODBC is a clutch.  You _must have_ matching drivers on _both sides_.  I much prefer direct connections which are more efficient too ... and that is why I proposed the topic and mentored the Google Summer of Code student who wrote the first variant of RPostgreSQL.  That package, now much extended, still works -- and I recommend that you install it (or one of the other packages connecting R to PostgreSQL).

**Comment by cboettig** [comment]
Hi Dan,

Thanks for the bug report.  Keep in mind if you're running RStudio from inside a rocker container, you need to pay attention to Docker container networking to set up connections, unless you're connecting to a public server. That said, this is super common thing to do, docker-compose makes it particularly easy with a separate container running postgres from the one running RStudio. e.g. here's a typical docker-compose file I use to run RStudio with connections to postgres and mariadb running in separate containers https://github.com/boettiger-lab/servers/blob/master/rstudio/docker-compose.yml (just note the `rstudio` and `postgres` bits, the other stuff is extraneous to this use case) .  The Official Docker docs also have a lot of examples on networking between compute and database containers. 

Once you've set up the containers, you can do this through any of a number of packages, `odbc` works great and integrates nicely with RStudio connections, but can also set up with DBI, which requires less setup.  Both are shown in the RStudio documentation you linked. Like Dirk says, you'll it's necessary software inside the container (e.g. client libs are included in `rocker/tidyverse` but not `rocker/rstudio`).  Apologies if this is all old hat, it's not quite clear what you mean by "working in R" (i.e. you mean it works in from running an R cli session inside the same Rocker container? Or just in a non-Dockerized R session?)

**Comment by danalexandrucraciun** [comment]
Hello Carl, Hello Dirk,

Thank your for the information provided, it's very helpful. I appreciate
your patience and please be kind as I am newborn on this topic: Rstudio / R

To make things clear :

- I am running Postgres in another container.  Rocket/rstudio is running on
a different container.
- I am considering the network layer, so there is no issue with that

Sorry for not explaining it right, I was referring to R, from
rocket/rstudio container, using the cli from rstudio. Here is the "code"
that I use to connect to db:

Loading required package: RPostgreSQL
> drv <- dbDriver("PostgreSQL")
> on <- dbConnect(drv, dbname = "***************************",
+                 host = "172.31.2.178", port = 5432,
+                 user = "***************", password = "***********")

I cleared the sensitive data with ****.

Like that, I was able to connect to the db an list the tables:

View(con)> dbListTables(con) [1] "master_lookup"
    "announcement"
 [3] "assigning_authority"                     "blacklisted"

Well, if I am going to connections tab, I see ODBC, when I click on it, it
asks for some new packages and I stuck here.

Having all this, do you suggest to run the container rocker/tidyverse with
the Rstudio add, instead of rocker/rstudio ?

Regards,
Dan

**Comment by cboettig** [comment]
@danalexandrucraciun thanks for clarifying.  we get questions from all levels so it's sometimes hard to know where folks are at.  Looks to me like you're connecting with RPostgreSQL directly over the DBI interface, rather than ODBC.  You can connect with ODBC if you want to, but you don't have to just to establish a connection.  

If you want to use ODBC, yeah, I think we have the necessary dependencies in rocker/tidyverse if you want to skip installing them manually -- I think that should have what you need to create a connection directly from the RStudio connections tab.  I believe the tab automatically picks up connections if you use ODBC, but that's also not the only way to 'register' a connection to the panel -- I believe they have functions in the `rstudioapi` package for that (e.g. see Noam's `citesdb` package for a really nice example of this: https://github.com/ropensci/citesdb/blob/master/R/connection-pane.R)  Of course, neither of these should be necessary just to connect from RStudio if you don't care about it showing up all pretty in the pane, you should be able to connect just like you do in CLI mode.  again apologies if I'm just saying stuff you already know.  

Also, since you're already on top of the whole container networking thing, this is all kinda outside the wheelhouse or rocker / container issues per se, so this would also be a good topic to ask about on RStudio community forum! (though comments are still welcome here! we should probably add something about setting this stuff up to the rocker documentation, including the postgres in separate container  setup part... contributions always welcome).

**Comment by danalexandrucraciun** [comment]
Hi Carl,

Thanks again for the documented answer.
Never had the intention to ask more than things related to rocker;  Rstudio information for sure could be found somewhere elese.

Even if I can connect to the db through RPostgresql, some of researchers colleagues, asked me to help them to create this odbc connection. That's why I decided to write to you, as dependences failed at installation and I thought that could be something related. 

I will deploy the rocker/tidyverse for testing the ODBC connection.

Thank you! Great job!
