### ISSUE TITLE
RStudio GPU image question

### ISSUE THREAD

**Issue by nik9jovanovic** [rocker-org/rocker#366]
Hello,

This is a general question. I've been using your docker images to setup rstudio on the cloud using AWS EC2 instances and so far it works great. I wanted to test out setting [tensorflow for R ](https://tensorflow.rstudio.com/tools/gpu.html)and use GPU instances as well. What would be the best approach to this? 

Since the images themselves do not have cuda installed, this would require changing the most base image (debian here) to some of the [nvidia/cuda](https://hub.docker.com/r/nvidia/cuda/) image, and then follow the Dockerfile steps all the way up to rocker/rstudio and then add tensorflow on top. The GPU instance would have to have nvidia drivers, nvidia docker runtime and docker installed and the image started with the runtime in order for it to be able to access the GPU. 

I just wanted to check if you know of some better approach or if there is a recommended image for this kind of analysis, or if it's planned in the future or if I should stick to my current plan for now.

Thanks!

**Comment by eddelbuettel** [comment]
Did you see these: https://hub.docker.com/r/rocker/ml  ?

**Comment by nik9jovanovic** [comment]
I didn't even know about these, they should fit my use-case perfectly. I will test them out and see if it helps, but the rocker/tensorflow-gpu and rocker/ml-gpu should be the ones I'm aiming for here.

Thank you very much @eddelbuettel!

**Comment by cboettig** [comment]
Thanks @nik9jovanovic , feedback welcome there, it's still a bit of a moving target.  Note that `rocker/tensorflow-gpu` and `rocker/ml-gpu` are based on cuda 9.0, you might also want to try out `rocker/ml:cuda-10.0` which is built on cuda 10.0 (as the tag suggests) and supports some of the newer libraries.  we're still figuring out how to triangulate tags and image names in this space since it involves a lot of moving parts, so feedback welcome!
