### ISSUE TITLE
Question: RStudio Server vs. RStudio Desktop choice?

### ISSUE THREAD

**Issue by dorianps** [rocker-org/rocker#367]
Hi everyone, and thanks for building rocker/rstudio. I have used that as a baseimage and works great.

While I use the RStudio Server container, I experimented a bit with RStudio Desktop and it was very easy to put an installation an a Ubuntu:16.04 baseimage and run it in Windows through X11 using MobaXterm.

I did this experiments because I needed other X11 apps, like ITKsnap, to run from the container. So, in principle it might be useful to have RStudio Desktop along other X11 apps. But since I don't find rstudio images that work with X11, and all the efforts here have gone to have docker with RStudio Server, I thought maybe there is some reason behind this choice. 

This is why I wanted to check the rationale why rocker has concentrated the efforts on the RStudio Server image? Is it because of future developments of RStudio might be going more towards the RStudio Connect style with multiple docker containers in the background, while the traditional GUI is be too restrictive for those future aims? Is it because it is more problematic to make X11 work on every platform? Is it because the GUI looks sharper an nicer on the browser than on X11?

Your experience and thoughts might help decide if it is worth investing time in keeping an alternative version of my images with RStudio Desktop besides the current ones I have with RStudio Server from rocker.

Thank you

P.s. I googled around and read this earlier thread as well, but can't find a clear rationale:
https://github.com/rocker-org/rocker/issues/118

**Comment by eddelbuettel** [comment]
Hm maybe you are overcomplicating it / reading too much into it?  To a first approximation, Docker is console / daemon only and does not do x11.  One can, of course, with some extra ellbow grease but it is just less common.  Hence RStudio Server in the browser.

(On my own Linux machines I use of course both RStudio Server and Desktop because it is easy to do.  That does not mean we must give as much weight to RStudio Desktop in rocker.)

**Comment by dorianps** [comment]
Got it, thanks.
