### ISSUE TITLE
R-base for PowerPC?

### ISSUE THREAD

**Issue by Someone894** [rocker-org/rocker#409]
Hello everyone,

for some time now I'm using your R-base image on my amd64 server.
For about the same time I use your [code ](https://github.com/rocker-org/rocker/blob/master/r-base/3.6.3/Dockerfile) as a basis for my own r-base image on an PowerPC 8 machine.
But lately this approach got more and more troublesome.

This leads me to the question:
Is it possible for you to supply the R-Base image for the PowerPC architecture as well?

This would be great.
Thank you for your time :-)

**Comment by eddelbuettel** [comment]
Does Docker Hub support builds for the cpu used on your PowerPC? I.e. what Debian calls ppc64el? 

Otherwise there is always a [direct installation of Debian on ppc64el](https://wiki.debian.org/ppc64el). Gets you *exactly* the same R packages as I maintain those in Debian where they are built for [20 or so architectures](https://buildd.debian.org/status/package.php?p=r-base).

**Comment by Someone894** [comment]
Sorry, but I don't really understand your question.

At the moment I am taking this [file](https://github.com/rocker-org/rocker/blob/master/r-base/4.0.2/Dockerfile) and change the `
FROM debian:testing` line to `FROM ppc64le/debian`. Then I hope, that it completes without any errors.

And now I was wondering if you could add a ppc66le version of your R-Base package to [Dockerhub](https://hub.docker.com/_/r-base). This way it would be tested and work more stable then my version. In addition to that other people could use it as well.

**Comment by eddelbuettel** [comment]
No because I cannot have _two versions of the same file_.

What I can do is turn on _two or more architectures to build_ from the *same* file.  That is how we support standard Intel x64 plus and arm variant:

```
Architectures: amd64, arm64v8
```

My question to you was (and still is) whether ppc64le is supported by Docker Hub?  If so I can add it.  If not, there is little I can do for you.

**Comment by Someone894** [comment]
The `ppc64le/debian` base image I use is from [dockerhub](https://hub.docker.com/_/debian?tab=tags), so I think it is possible to deploy ppc64le via dockerhub.

I also found some documentation [here](https://github.com/docker-library/official-images#architectures-other-than-amd64) which suggests that ppc64le is part of "Other architectures built by official images: (but not officially supported by Docker, Inc.)". 

Therefore I think that ppc64le is supported by Docker Hub.

**Comment by eddelbuettel** [comment]
Thanks for the documentation pointer -- that was exactly what I needed.

PR filed, if and when it is merged by the Docker maintainers you will get `r-base` for ppc64le.

**Comment by eddelbuettel** [comment]
This has been merged upstream so you should have `r-base` for pp64le now, or "very soon".
