### ISSUE TITLE
rocker/rstudio doesn't work on M1 Mac (arm) architecture

### ISSUE THREAD

**Issue by steve273** [rocker-org/rocker#450]
Hello, having an issue with logging into Rstudio once the docker is running. When I run:

`docker run --rm -p 8787:8787 -e PASSWORD=yourpasswordhere rocker/rstudio`

Then open browser and try to log in with "rstudio" and specified password, I get the following error:

`Error: Incorrect or invalid username/password`

I see no errors in terminal or docker desktop. Running macOS 11.2.3.

**Comment by cboettig** [comment]
Sorry but I cannot reproduce this.  Can you try:

- starting with a fresh `docker pull rocker/rstudio`
- clear cache or open a fresh 'private window' so we have a clean cache
- log in there?

Since you're running on a local machine, can you also try logging in without auth and see if that works?

```
docker run --rm \
  -p 127.0.0.1:8787:8787 \
  -e DISABLE_AUTH=true \
  rocker/rstudio
  ```


(note that binding to 127.0.0.1:8787 makes sure your connection is not available to other machines over the network, and we no longer need to bother with a password like we do on a remote server connection).

**Comment by steve273** [comment]
Thanks for quick reply. I performed a fresh pull command and using a private window, still have the same error when I log in there. 

When I use the second command to log in without authorization, I get the following:

"Rstudio Initialization Error"
"Unable to connect to service"

Is there any additional information I can provide to help? Currently have docker desktop version 3.3.1 (63152).

**Comment by cboettig** [comment]
Very weird, sounds like issues we usually see with cache from another instance.  This is an intel-based mac? Lots of things we might try but since I can't reproduce in the first place I'm shooting in the dark here.  

consider restarting the docker daemon, making sure to stop any active rocker containers, and try first in a private window binding without auth to an alternate port (here localhost:8888):

```
docker run --rm \
  -p 127.0.0.1:8888:8787 \
  -e DISABLE_AUTH=true \
  rocker/rstudio
```

**Comment by steve273** [comment]
Ah, maybe that's it. Using an arm based Mac. Might need to use another platform until these images are available for arm64?

**Comment by cboettig** [comment]
It could be, I can't say for sure, some aspects should be platform independent but others are not. 
One last thing to check would be to confirm that this fails on one of the older, frozen images, e.g. rocker/rstudio:3.6.3

**Comment by steve273** [comment]
Still getting error:

"Rstudio Initialization Error"
"Unable to connect to service"

I've used other and images with the docker virtualization layer without a problem. This seems like such a specific error, I wish I could help narrow it down further.

**Comment by eitsupi** [comment]
Is this the same problem?
https://github.com/rocker-org/rocker-versioned2/issues/144

**Comment by steve273** [comment]
Based on the screen shots in the other issue, yes, seeing the same thing here.

**Comment by earnold** [comment]
Not sure if this is helpful, but I can confirm I'm experiencing the same issue on an M1 mac as well.

**Comment by dcaud** [comment]
Isn't Docker supposed to prevent just this kind of problem?

**Comment by cboettig** [comment]
@dcaud no, I'm afraid not.  `docker` can provide you a virtual linux-like environment on a mac or windows machine, but this is an issue about actual hardware.  Docker systems have to build different image binaries for arm vs intel, just like other software. RStudio-server binaries are unfortunately not available on M1 macs yet, so we cannot package them in docker.  Of course the RStudio team is aware of this, so keep an eye on https://github.com/rstudio/rstudio/issues/8809 and hope we'll be able to build arm-based images with RStudio-server soon!

**Comment by yufree** [comment]
Hi, following previous post, RStudio start building arm-based RStudio-server experimental binaries [now](https://github.com/rstudio/rstudio/issues/8809#issuecomment-1218410557).

**Comment by eitsupi** [comment]
duplicate of rocker-org/rocker-versioned2#144
Please check that issue.
