### ISSUE TITLE
Suggestion: Use debian:stable for r-base docker images

### ISSUE THREAD

**Issue by kavi** [rocker-org/rocker#469]
From rocker/tidyverse docs:

> builds on debian stable (debian:jessie for versions < 3.4.0, debian:stretch after, etc) release instead of debian:testing, so no more apt-get breaking when debian:testing repos are updated and you had to muck with -t unstable to get apt-get to work.

This just seems like a good idea. There is also the fact that some packages may not yet be available for Debian bookworm, and while packages from Debian 11 might work in some cases, they may not in other.

**Comment by eddelbuettel** [comment]
Please see our [RJournal paper](https://journal.r-project.org/archive/2017/RJ-2017-065/index.html)  -- the versioned(2) stack is distinct from the base stack so using arguments from one to the other does not quite "match".

The base stack is happy with its choices. If you have actual bug (preferably with a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) let us know and feel free to reopen.  Otherwise, I am afraid it is an issue that has been discussed (several times).  Thanks for your interest in Rocker and r-base.
