### ISSUE TITLE
suggestion box: private package repository container

### ISSUE THREAD

**Issue by andrewcstewart** [rocker-org/rocker#79]
Just an idea for the backlog, but a container for creating personal package repositories could be very useful.

**Comment by cboettig** [comment]
@andrewcstewart Just for fun, a dockerized r-repo (e.g. Docker container running an apache server): https://github.com/cboettig/dockerfiles/tree/master/r-repo 

Like Dirk points out though, such R repositories are simply a static file structure following certain conventions, so Docker isn't very relevant. For instance, rather than run your own apache server, one could just drop those binaries onto Github: https://github.com/yihui/xran (not suggesting that's a good idea or not, but illustrates the point)
