### ISSUE TITLE
how to install gsl?

### ISSUE THREAD

**Issue by benmarwick** [rocker-org/rocker#93]
In attempting to install the `topicmodels` and `gsl` packages I've found I need the gsl libraries. 

I tried to install them at the command line with the running container using `docker exec -it "id of running container" bash` to get a bash shell and then downloading gsl-1.9 and installing following the instructions [here](http://stackoverflow.com/questions/24781125/installing-r-gsl-package-on-mac). But it's not making any difference in RStudio or R started from the shell. What else should I try?

```
docker@boot2docker:~$ docker ps
CONTAINER ID        IMAGE                       COMMAND                CREATED
           STATUS              PORTS                    NAMES
4d07e0a3d08a        rocker/hadleyverse:latest   "/usr/bin/supervisor   2 days ag
o          Up 2 days           0.0.0.0:8787->8787/tcp   pensive_carson
docker@boot2docker:~$ docker version
Client version: 1.3.1
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 4e9bbfa
OS/Arch (client): linux/amd64
Server version: 1.3.1
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 4e9bbfa
docker@boot2docker:~$
```

**Comment by bbolker** [comment]
Out of curiosity, is there a diagnosis/solution to this problem?

> E: The value 'testing' is invalid for APT::Default-Release as such a release is not available in the sources

(trying this in `rocker/r-base` ... will go try out `hadleyverse` instead in case it has gsl already ...

**Comment by eitsupi** [comment]
This issue is from the prehistoric past, 10 years ago......
I think the situation today is very different than it was then. Check the project website.
https://rocker-project.org/use/extending.html

**Comment by bbolker** [comment]
Thanks. Doing it the old-fashioned way was fine for me as I was doing a one-off test. I appreciate the link to the modern way of doing things, as I am relatively inexperienced with Docker, but I would have to spend some time experimenting/getting up to speed with `docker build` etc. ...

**Comment by eddelbuettel** [comment]
@bbolker If you resurrect ten year old post, would you be so kind to supply a minimally verifiable complete example to?
Right now I have less than zero visibility into what you did to trigger that.

Now if I may, and extending what @eitsupi already said:

1. You are a decades long user of Debian / Ubuntu / PopOS.  You surely know about `apt-cache search libsgl`?  Maybe you know also about `apt-cache rdepends libgsl27` (using a concrete current package) ?
2. For what it is worth, I provide r2u _precisely_ so that those issues become non-issues.  Any installation via `install.packages(foo)` for any package foo depending on `libgsl` _will_ in fact bring `libgsl` in.  Reliably.  Why not take advantage?
3. For what it is worth part two, Inaki's `rspm` does the without the system manager (as it can't) but for a broader set of distributions.  Out of curiousity, I just validated that on a Debian-based Rocker container yesterday. It also works reliably (via a two-step process using `apt` tools rather than the direct r2u route).
4.  Consider asking R and Debian questions on r-sig-debian too.  You will get more eyeballs on it there and possibly get a wider feedback than from just @eitsupi and myself.

**Comment by bbolker** [comment]
sorry, I had tried to indicate by my "never mind" comment, and by my reply to @eitsupi, that the problem was now resolved (since this issue was already closed I couldn't re-close it). Finding `libgsl0-dev` wasn't the proximal problem, the error message which I quoted was (which I resolved from #134 by remembering to `apt-get upgrade`.  

I will probably use `r-bspm:testing` in the future now that I know about it.

**Comment by eddelbuettel** [comment]
I think you meant `apt update`.  That collects the indices avoiding 'what is testing' issue.

There is no `r-bspm:testing`.  Did you mean `rspm` ?

**Comment by bbolker** [comment]
Yes, I did mean `apt update`.

As for the latter, I meant this: https://github.com/rocker-org/bspm which refers to `docker pull rocker/r-bspm:testing`

**Comment by eddelbuettel** [comment]
Yes but that container was a) not updated in two years (as it was more or less a precursor to r2u) and b) can (as I tried to explain) only serve what `r-cran-*` is available.  Same as `rocker/r-base`:

```sh
$ docker run --rm -ti rocker/r-base bash -c 'apt update -qqq; apt-cache search r-cran-* | wc -l'
1130
$ 
```

The maintenance standard between those `r-cran-*` packages can also vary.   

While you still have not told us what you _really_ want to do I feel that the thread (in a ten year old issue...) has run its course now.  If `rocker/r-bspm` does serve your need that I will remain glad and happy to have been of assistance.

**Comment by bbolker** [comment]
I've definitely solved my problem, and had already succeeded as of [this post](https://github.com/rocker-org/rocker/issues/93#issuecomment-2132250157) (and tried to indicate [here](https://github.com/rocker-org/rocker/issues/93#issuecomment-2132288075) that the question was resolved). All I wanted to do was install the `gsl` package in a rocker image. I now have at least three ways to do that (brute-force via `apt update; apt-get install libgsl0-dev` + `install.packages()` from within R; use a Dockerfile to install `libgsl0` as suggested by @eitsupi; use `r-r2u`).  Thanks.
